<?php
$list = $this->list;
?>
<div class="row">
    <div class="span12">
        <div class="widget-block">
            <div class="widget-content">
                <div class="widget-selectbox">
                    <ul>
                        <a class="btn btn-primary" href="<?php echo $this->contextPath ?>/add"><i class="icon-plus icon-white"></i> Add New</a>
                        <li class="right">
                            <form action="#" method="get">
                                <div class="input-prepend"> <span class="add-on"><i class="icon-list-alt"></i></span>
                                    <select name="" class="data-select">
                                        <option value="Done">Done</option>
                                        <option value="Pending">Pending</option>
                                    </select>
                                </div>
                            </form>
                        </li>
                    </ul>
                </div>
                <div class="widget-box">
                    <table class="table task-tbl post-tbl table-striped">
                        <thead>
                            <tr>
                                <th width="5%">
                                    #
                                </th>
                                <th width="">
                                    Name VI
                                </th>
                                <th width="">
                                    Name EN
                                </th>
                                <th width="">
                                    Name JP
                                </th>
                                <th width="20%" class="align-center" style="color: red; font-weight: bold;">
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($list):
                                $i = 1;
                                foreach ($list AS $item) {
                                    ?>
                                    <tr>
                                        <td class="align-center sorting_1"><?php echo $i ?></td>
                                        <td <?php if ($item['parent_id'] == 0) echo 'style="color: red; font-weight: bold;"' ?>><?php echo $item['name_vi'] ?></td>
                                        <td <?php if ($item['parent_id'] == 0) echo 'style="color: red; font-weight: bold;"' ?>><?php echo $item['name_en'] ?></td>
                                        <td <?php if ($item['parent_id'] == 0) echo 'style="color: red; font-weight: bold;"' ?>><?php echo $item['name_jp'] ?></td>
                                        <td class="action align-center">
                                            <a href="<?php echo $this->contextPath ?>/edit?id=<?php echo $item['id']; ?>" class="btn btn-success">
                                                <i class="icon-edit icon-white"></i> Edit
                                            </a>
                                            &nbsp;
                                            <a rel='<?php echo $this->contextPath ?>/delete?id=<?php echo $item['id'] ?>' class="btnDeleteRow btn btn-danger" href="javascript://">
                                                <i class="icon-trash icon-white"></i> Delete
                                            </a>
                                        </td>
                                    </tr>
                                    <?php
                                    $i++;
                                }
                                ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>