<!-- SLIDER DOWNLOAD BEGIN -->
<section id="download_slider_box">
    <div class="center">
        <div class="download">
            <h1 class="element_from_left">Kiếm tiền với eDoctor</h1>
            <p>
			eDoctor hiện đang có hơn 200 tài khoản đăng ký Affiliate Marketing, hơn 300 đại lý phân phối trực tiếp <a target="_blank" href="http://edoctor.vn/the-cham-soc-suc-khoe-edoctor.htm">thẻ chăm sóc sức khỏe eDoctor</a> trên toàn quốc và không ngừng tăng lên mỗi ngày...
			</p>
            <a href="#contact_us" class="btn_big element_from_right">Tham gia ngay</a>
        </div>
        <div class="download_slider_box element_from_left">
            <div id="download_slider">
                <div class="slide" id="download1">
                	<!-- 1st download slider image change here -->
                    <img alt="the tu van cham soc suc khoe edoctor" src="/layouts/affiliate_landing/img/slide5.png" alt="" />
                    <span>Cơ hội <b>hợp tác lâu dài</b></span>
                </div>
                <div class="slide" id="download2">
                	<!-- 2nd download slider image change here -->
                    <img alt="cham soc suc khoe ba bau" src="/layouts/affiliate_landing/img/slide7.png" alt="" />
                    <span><b>Lĩnh vực đầy tiềm năng</b>, đem lại nhiều giá trị</span>
                </div>
                <div class="slide" id="download3">
                	<!-- 3rd download slider image change here -->
                    <img alt="kiem tien online" src="/layouts/affiliate_landing/img/slide6.png" />
                    <span><b>Chiết khấu cao</b> thanh toán nhanh gọn</span>
                </div>
            </div>
            <div id="pager3" class="pager"></div>
        </div>
    </div>
</section>
<!-- SLIDER DOWNLOAD END -->
<!-- BENEFITS BLOCK BEGIN -->

            <section id="benefits" class="box">
                <div class="center">
                    <h2>Tại sao bạn nên hợp tác với eDoctor ?</h2>
                    <div class="benefits_box">
                    
                    	<!-- Benefit 1-->
						<div class="benefit element_from_left">
                            <span class="fa fa-users"></span>
                            <h3>Thị trường tiềm năng</h3>
                            <p>Trên 90% phụ nữ sống tại các thành phố lớn quyết định toàn bộ việc chăm sóc sức khỏe cho gia đình, 
							họ thường xuyên có <strong>nhu cầu tiếp nhận các thông tin y tế</strong> và sử dụng các dịch vụ tư vấn chăm sóc sức khỏe, thẻ chăm sóc sức
                            khỏe eDoctor đã ra đời và giải quyết nhu cầu đó. 
							</p>
                        </div>
						
                        <!-- Benefit 2-->
                        <div class="benefit element_from_bottom">
                            <span class="fa fa-thumbs-up"></span>
                            <h3>Ít rủi do</h3>
                            <p>Bạn không cần có sản phẩm. <br> 
                            Bạn chỉ cần đăng ký <i class="fa fa-long-arrow-right"></i> lấy link affiliate <i class="fa fa-long-arrow-right"></i> quảng bá tới những khách hàng có nhu cầu <i class="fa fa-long-arrow-right"></i> Nhận tiền hoa hồng. <br>
                            Chỉ cần quảng cáo: bạn không phải giao hàng, hỗ trợ - những việc này là trách nhiệm của eDoctor.
							</p>
                        </div>
                        
                        <!-- Benefit 3-->
                        <div class="benefit element_from_right">
                            <span class="fa fa-shopping-cart"></span>
                            <h3>Hiệu quả cao</h3>
                            <p>Với thị trường đầy tiềm năng, tập khách hàng là những người có thu nhập từ khá trở lên, họ sẵn sàng trả tiền để sử dụng những dịch vụ hữu ích và tiện lợi như thẻ eDoctor. Mức tiền hoa hồng cho mỗi sản phẩm được bán rất hấp dẫn. Bạn hoàn toàn có thể có một mức thu nhập khá mỗi tháng từ eDoctor.
							</p>
                        </div>
                    </div>
					<h2 style="margin-top:30px; display:block;">Hợp tác phân phối thẻ eDoctor như thế nào ?</h2>
                    <div class="benefits_box">
						<!-- Benefit 1-->
                        <div class="benefit element_from_bottom">
                            <span class="fa fa-user"></span>
                            <h3>Đăng ký với eDoctor</h3>
                            <p>Quá trình bao gồm các bước: đăng ký tài khoản Affiliate của eDoctor, 
							đàm phán chính sách hợp tác và kết nối kỹ thuật, kênh thanh toán, sau đó nhận link (link aff) của riêng bạn.
							</p>
                        </div>
                        
                        <!-- Benefit 2-->
                        <div class="benefit element_from_top">
                            <span class="fa fa-share-alt"></span>
                            <h3>Quảng bá thẻ eDoctor</h3>
                            <p>Cùng với các chiến dịch marketing, truyền thông... đã và đang triển khai của eDoctor. Bạn sẽ dễ dàng giới thiệu link aff đến khách hàng.
							</p>
                        </div>
                        
                        <!-- Benefit 3-->
                        <div class="benefit element_from_bottom">
                            <span class="fa fa-usd"></span>
                            <h3>Nhận tiền</h3>
                            <p>Mỗi khi khách hàng mua thẻ eDoctor qua đường link của bạn, bạn sẽ nhận được hoa hồng của eDoctor theo mức đã thỏa thuận.</p>
                        </div>
						
					</div>
				</div>
            </section>

<!-- BENEFITS BLOCK END -->
<!-- VIDEO BLOCK BEGIN -->

            <section id="video" class="box">
                <div class="center">
                    <div class="video_info">
                        <h2 class="element_from_top">Thẻ chăm sóc sức khỏe eDoctor</h2>
                        <p class="element_from_left"><i class="fa fa-hand-o-right"></i> Đội ngũ trên 500 giáo sư, bác sĩ trên toàn quốc và ngày càng tăng lên...</p>
                        <p class="element_from_left"><i class="fa fa-hand-o-right"></i> Nhận được ưu đãi, giảm giá tại các phòng khám, trung tâm thẩm mỹ, Spa... đối tác của eDoctor</p>
						<p class="element_from_left"><i class="fa fa-hand-o-right"></i> Và rất nhiều tính năng hấp dẫn khác đang chờ bạn khám phá..</p>
                    </div>
                    <div class="video_box element_from_bottom">
						<img alt="cham soc suc khoe ba bau" src="/layouts/affiliate_landing/img/the-tu-van-cham-soc-suc-khoe-edoctor.png">
					</div>
                </div>
            </section>

<!-- VIDEO BLOCK END -->
			<section id="opinions" class="box">
				<div class="center">
					<h2>Các đối tác nói gì về eDoctor ?</h2>
					<div class="reviews_box">
						<div class="reviews_item element_from_left">
							<div class="reviews_text">
								<p>Mô hình hoạt động của eDoctor sẽ giúp giảm tải cho các bệnh viện, cung cấp những kiến thức sức khỏe đáng tin cậy cho người dân. Chúng tôi đánh giá cao ý tưởng này, chúc eDoctor phát triển hơn nữa, giúp được nhiều người hơn nữa...</p>
								<span class="review_icon fa fa-quote-left"></span>
								<span class="review_arrow"></span>
							</div>
							<div class="review_autor">
								<a href="#"><img alt="cuc cong nghe thong tin" src="/layouts/affiliate_landing/img/partner1.jpg" alt=""></a>
								<p>Cục Công nghệ thông tin – Bộ Y tế</p>
							</div>
						</div>
						<div class="reviews_item element_from_right">
							<div class="reviews_text">
								<p>Là những thầy thuốc, bác sĩ trẻ.. chúng tôi rất muốn tiếp xúc nhiều hơn để hiểu hơn về bệnh nhân, từ đó chuẩn đoán và đưa ra 
                                    các liệu pháp điều trị phù hợp, tích lũy kinh nghiệm. Cảm ơn eDoctor đã cho chúng tôi cơ hội quý báu đó!
                                </p>
								<span class="review_icon fa fa-quote-left"></span>
								<span class="review_arrow"></span>
							</div>
							<div class="review_autor">
								<a href="#"><img alt="hoi thay thuoc tre viet nam" src="/layouts/affiliate_landing/img/partner2.jpg" alt=""></a>
								<p>Hội Thầy thuốc trẻ</p>
							</div>
						</div>
					</div>
				</div>
			</section>
<!-- CONTACT US BLOCK BEGIN -->
            <section id="contact_us" class="box">
                <div class="center">
                    <h2>Liên hệ với eDoctor</h2>
                    <div class="contact_info" itemscope itemtype="http://schema.org/Organization">
                        <ul>
                            <li itemprop="address">
                                <span class="fa fa-map-marker"></span> Số 23, ngách 37/2, phố Dịch Vọng, Cầu Giấy, Hà Nội, Việt Nam
                            </li>
                            <li itemprop="email"><a href="mailto:hotro@edoctor.vn"><span class="fa fa-envelope"></span> hotro@edoctor.vn</a></li>
                            <li itemprop="telephone"><a href="tel:0466739922"><span class="fa fa-phone"></span> (04) 6673-9922</a></li>
                            <li><a href="khuongkk"><span class="fa fa-skype"></span> khuongkk</a></li>
                        </ul>
                    </div>
 	
                    <div style="display:none" class="map" id="map-canvas"></div>
					<form action="" method="post" id="contact_form">
                            <div>
								<input type="text" placeholder="Họ tên"/>
                                <input type="text" placeholder="Số điện thoại"/>
								<br />
								<input style="" type="text" placeholder="Email"/>
								<br />
								<textarea placeholder="Nội dung liên hệ"></textarea>
                                <input type="submit" value="Gửi liên hệ" class="btn_grey"/>
                            </div> 
                        </form>
                </div>
            </section>
<!-- CONTACT US BLOCK END -->
<div class="footerHeight"></div>