<?php 
$article = $this->article;
$listLQ  = $this->listLQ;
 ?>
<h1 id="page-title"><?php echo $article->art_name?></h1>
<!-- ARTICLE -->
<div id="article" class="curvyRedraw">
	<?php echo $article->art_content?>
	<p style="border-top:1px solid #ddd; padding-top:10px;"><strong>Dùng thử dịch vụ trong 24h đầu</strong></p> 
	<a class="m-btn" href="tel:18006115" title=""><i class="fa fa-phone"></i> 18006115 (miễn phí)</a>
	<br />
	<p><strong>Đặt mua thẻ eDoctor</strong></p>
	<a class="btn-cam" href="/onepage.htm" title="Mua thẻ eDoctor">Mua thẻ eDoctor</a>
	<p class="note">
		<strong>Hoàn trả 100%</strong> giá trị thẻ eDoctor trong 30 ngày đầu tiên nếu khách hàng không hài lòng và không muốn sử dụng dịch vụ của eDoctor.
	</p>
</div>
<!-- END ARTICLE -->