<?php 
$totalRecords = $this->totalRecords;
$recordPerPage = $this->recordPerPage;
$pageNum = $totalRecords/$recordPerPage;
?>
	<h1 class="full" id="page-title"><strong>Giải đáp thắc mắc sức khoẻ từ bác sỹ eDoctor</strong></h1>
	<div class="clear"></div>
	</div><!--end rwidth head post-->
</div>
<!--end head post-->
<div class="padding">
	<div class="khuongnt_content services full">
		<div class="rwidth">
			<div class="col col700 the_content">
				<h2 style="font-size:20px; margin-top:0;"><strong>Bạn đang có những thắc mắc về sức khoẻ?</strong></h2>
				<div class="success">
					<p style="margin-bottom:0;">Để có câu trả lời ngay lập tức hãy gọi về số <strong>18006115</strong>  (miễn phí cước gọi - miễn phí dùng thử 24h đầu) hỏi trực tiếp các bác sỹ của eDoctor.</p>
				</div>
				
				<div class="full">
					<h2 style="font-size:20px;">Những giải đáp thắc mắc về sức khoẻ mới nhất từ các bác sỹ eDoctor</h2>
					<ul class="list-cauhoi">
						<?php if(isset($this->qaList)):
						foreach ($this->qaList as $key => $qaLists): 
							$phone = str_replace(substr($qaLists['qa_phone'], -4, 4), '****', $qaLists['qa_phone']);
						?>
						<li>
                            <div class="qa_quest full">
                            	<h3><i class="fa fa-question-circle"></i> Bạn <?php echo $qaLists['qa_name']; ?> hỏi</h3>
                            	<span class="qa_meta"><?php if($phone) { ?>SĐT: <?php echo $phone; ?> - <?php } ?><?php echo date("d-m-Y H:i", $qaLists['qa_time']); ?></span>
	                            <div class="content_quest full">
	                            	<p><?php echo $qaLists['qa_content'];?></p>
	                            	<a class="more_quest" href="#" title="">Xem thêm <i class="fa fa-chevron-down"></i></a>
	                            </div>
                            </div>
                            <div class="qa_answer full"> 
                            	<div class="content-answer">
                            		<h4><i class="fa fa-comments-o"></i> Trả lời từ bác sỹ eDoctor</h4>
                            		<div class="container_answer">
                            			<?php echo $qaLists['qa_answer'];?>
                            		</div>
                            		<a class="more_answer" href="#" title="">Xem thêm <i class="fa fa-chevron-down"></i></a>
                            	</div>
                            </div>
						</li>
						<?php endforeach; endif; ?>
					</ul>
					<div class="pagination">
                        <ul class="pagination">
                            <?php if($pageNum > 1): 
                            for ($i=1; $i <= $pageNum; $i++) { ?>
                                <li <?php if( isset($_GET['page']) && $i == $_GET['page']) echo 'class="active"'; ?>><a href="/giai-dap-thac-mac-suc-khoe.html?page=<?php echo $i; ?>"><?php echo $i; ?></a></li>
                            <?php } ?>
                            <?php else: ?>
                            <?php endif; ?>
                        </ul>
                    </div>
				</div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>
</article>
<div class="clear"></div>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$('.content_quest > p').each(function() {
			if($(this).height() > 120) {
				$(this).css('height', '120px');
			} else {
				$(this).next('a').hide();
			}
		});
		$('.container_answer').each(function() {
			if($(this).height() > 135) {
				$(this).css('height', '135px');
			} else {
				$(this).next('a').hide();
			}
		});
		$('.more_quest').click(function() {
			if($(this).hasClass('active')) {
				$(this).prev('p').css('height', '120px');
				$(this).removeClass('active');
				$(this).html('Xem thêm <i class="fa fa-chevron-down"></i>')
			} else {
				$(this).prev('p').css('height', 'auto');
				$(this).addClass('active');
				$(this).html('Thu gọn <i class="fa fa-chevron-up"></i>');
			}
			return false;
		});
		$('.more_answer').click(function() {
			if($(this).hasClass('active')) {
				$(this).prev('div').css('height', '140px');
				$(this).removeClass('active');
				$(this).html('Xem thêm <i class="fa fa-chevron-down"></i>')
			} else {
				$(this).prev('div').css('height', 'auto');
				$(this).addClass('active');
				$(this).html('Thu gọn <i class="fa fa-chevron-up"></i>');
			}
			return false;
		});
	});
</script>