<?php $list = $this->list;?>
<h1 id="page-title"><strong>Đội ngũ bác sĩ</strong></h1>
<div id="left-content">	
	<div class="khuongnt_content doctor full">
		<div class="list-bacsi full">
			<h2 class="title-bs">Một số bác sĩ tiêu biểu đang tham gia tư vấn chăm sóc sức khỏe cho eDoctor</h2>
			<a class="m-btn" href="tel:18006115" title=""><i class="fa fa-phone"></i> 18006115 (miễn phí)</a>
			<br />
			<div class="item-bacsi full">
				<img src="/upload/images/bac-si-tu-van-suc-khoe-duong-trong-hieu.jpg" alt="">
				<div class="info-bs">
					<h2>Giáo sư, Tiến sỹ Dương Trọng Hiếu</h2>
					<span>Bác sỹ chuyên khoa Nội Y học cổ truyền - Viện nghiên cứu Đông y, nay là Bệnh viện Y học cổ truyền Trung ương</span>
				</div>
			</div>
			<!--end doctor item-->
			<div class="item-bacsi full">
				<img src="/upload/images/bac-si-tu-van-suc-khoe-nguyen-thi-ngoc-dinh.jpg" alt="">
				<div class="info-bs">
					<h2>Phó GS, Tiến sỹ Nguyễn Thị Ngọc Dinh</h2>
					<span>Thầy thuốc ưu tú chuyên khoa Tai mũi họng, nguyên Giám đốc Bệnh viện Tai Mũi Họng Trung ương, nguyên chủ nhiệm Bộ môn Tai Mũi Họng – Học viện Quân y </span>
				</div>
			</div>
			<!--end doctor item-->
			<div class="item-bacsi full">
				<img src="/upload/images/bac-si-tu-van-suc-khoe-tran-cong-hoa.jpg" alt="">
				<div class="info-bs">
					<h2>Phó giáo sư, Tiến sỹ Trần Công Hòa</h2>
					<span>Nguyên trưởng khoa Thanh học – Bệnh viện Tai Mũi Họng Trung ương, tổng thư ký Hội Tai Mũi Họng Việt Nam, ủy viên Thường vụ Hội Tai Mũi Họng Hà Nội
					</span>
				</div>
			</div>
			<!--end doctor item-->
			<div class="item-bacsi full">
				<img src="/upload/images/bac-si-tu-van-suc-khoe-le-hiep-dung.jpg" alt="">
				<div class="info-bs">
					<h2>Thạc sỹ, bác sỹ chuyên khoa II Lê Hiệp Dũng</h2>
					<span>Bác sỹ chuyên khoa Nội – Bệnh viện Việt Nam – Cuba. Trưởng khoa Tim mạch – Bệnh viện Thanh Nhàn. Hội viên Hội Tim mạch Việt Nam. Ủy viên Ban chấp hành Hội Tim mạch Hà Nội
					</span>
				</div>
			</div>
			<!--end doctor item-->
			<div class="item-bacsi full">
				<img src="/upload/images/bac-si-tu-van-suc-khoe-do-phuong-mai.jpg" alt="">
				<div class="info-bs">
					<h2>Thạc sỹ, Bác sỹ chuyên khoa II Đỗ Phương Mai</h2>
					<span>Thạc sỹ, Bác sỹ chuyên khoa II, trưởng khoa Nội C Bệnh viện Giao thông vận tải Hà Nội
					</span>
				</div>
			</div>
			<!--end doctor item-->
			<div class="item-bacsi full">
				<img src="/upload/images/bac-si-tu-van-suc-khoe-cao-tien-duc.jpg" alt="">
				<div class="info-bs">
					<h2>Phó giáo sư, tiến sỹ Cao Tiến Đức</h2>
					<span>Phó giáo sư, tiến sỹ, bác sỹ cao cấp - Giảng viên bộ môn Tâm thần học Học viện Quân y 103. Chủ nhiệm khoa Thần kinh - Tâm thần A6 – Bệnh viện Quân y 103. Phó Chủ tịch Hội đồng giám định của Bộ Quốc phòng.
					</span>
				</div>
			</div>
			<!--end doctor item-->
			<div class="item-bacsi full">
				<img src="/upload/images/bac-si-tu-van-suc-khoe-pham-xuan-quy.jpg" alt="">
				<div class="info-bs">
					<h2>Tiến sỹ Phạm Xuân Quý</h2>
					<span>Tiến sỹ y học chuyên ngành Sinh lý học, Bác sỹ Chuyên khoa II Ngoại sản, Bác sỹ Bộ Giao thông Vận tải. Chuyên gia y tế Tổng Công ty Hàng không Việt Nam. Giám đốc Công ty Cổ phần y tế Việt Mỹ
					</span>
				</div>
			</div>
			<!--end doctor item-->
			<div class="item-bacsi full">
				<img src="/upload/images/bac-si-tu-van-suc-khoe-pham-thi-minh-phuong.jpg" alt="">
				<div class="info-bs">
					<h2>Tiến sỹ Phạm Thị Minh Phương</h2>
					<span>Bác sỹ chuyên khoa Da liễu – Bệnh viện Da liễu Trung ương. Trưởng phòng Hợp tác quốc tế - Bệnh viện Da liễu Trung ương
					</span>
				</div>
			</div>
			<!--end doctor item-->
			<div id="hide_side" class="item-bacsi full">
				<img src="/upload/images/bac-si-tu-van-suc-khoe-kieu-dinh-khoan.jpg" alt="">
				<div class="info-bs">
					<h2>Thạc sỹ, Bác sỹ chuyên khoa II Kiều Đình Khoan</h2>
					<span>Bác sĩ điều trị, phó trưởng khoa Nội - Bệnh viện Y học cổ truyền Trung ương. Bác sĩ điều trị, trưởng khoa Người có tuổi; Bí thư Chi Bộ. Đảng uỷ viên, phó chủ tịch Công Đoàn Bệnh viện Y học cổ truyền Trung ương
					</span>
				</div>
			</div>
			<!--end doctor item-->
			<div class="item-bacsi full">
				<img src="/upload/images/bac-si-tu-van-suc-khoe-nguyen-vu.jpg" alt="">
				<div class="info-bs">
					<h2>Thạc sỹ, Bác sỹ Nguyễn Vũ</h2>
					<span>Giảng viên Bộ môn Ngoại, Đại học Y Hà Nội, nguyên Phẫu thuật viên Khoa Phẫu thuật thần kinh Bệnh viện Việt Đức, bác sỹ, phẫu thuật viên Khoa Ngoại, Bệnh viện Đại học Y Hà Nội
					</span>
				</div>
			</div>
			<!--end doctor item-->
			<p>..Và hàng trăm bác sỹ khác đang tham gia vào đội ngũ bác sỹ tư vấn chăm sóc sức khỏe của eDoctor, hình ảnh, thông tin của bác sỹ đang được chúng tôi thu thập thêm và sẽ được cập nhật lên website ngay sau khi có đầy đủ thông tin...</p>
			<p>Tất cả các giáo sư, tiến sỹ, thạc sỹ, bác sỹ đều là các <strong>bác sỹ cao cấp</strong> đã và đang làm việc tại các bệnh viện hàng đầu trên toàn quốc, có kiến thức chuyên sâu về từng khoa khác nhau, họ là những thầy thuốc tận tụy hết mình vì bệnh nhân, luôn luôn mong muốn cứu chữa được cho nhiều người.</p>
			<br />
			<p style="text-align:center;">
				<img style="border-radius:3px;" src="/upload/images/bac-si-nguyen-vu-tham-benh-nhan-sau-phau-thuat.jpg" alt=""> <br />
				<span style="font-size:12px;"><i>Bác sỹ Nguyễn Vũ cùng các đồng nghiệp thăm bệnh nhân sau ca phẫu thuật thành công</i></span>
			</p>
			<br />
			<a class="m-btn" href="tel:18006115" title=""><i class="fa fa-phone"></i> 18006115 (miễn phí)</a>
			<br />
			<p>Chúng tôi đã rất may mắn và thuyết phục được các bác sỹ hợp tác cùng với eDoctor. Hy vọng với đội ngũ bác sĩ đông đảo, giàu kinh nghiệm, chuyên môn hàng đầu.. mọi thắc mắc của quý khách hàng đều được giải đáp. Ngay từ bây giờ bạn có thể gọi điện thoại về tổng đài <strong>18006115</strong> để dùng thử <strong>MIỄN PHÍ</strong> dịch vụ tư vấn chăm sóc sức khỏe của chúng tôi trong vòng 24h kể từ cuộc gọi đầu tiên (Miễn phí cước gọi).</p>
			<div style="margin-bottom:10px;" class="muathe">
				<a class="btn-cam" href="/mua-the.htm" title="Mua thẻ eDoctor">Mua thẻ eDoctor</a>
			</div>
			<p class="note">Trong thời gian <strong>30 ngày</strong> kể từ ngày kích hoạt thẻ eDoctor, nếu quý khách hàng không hài lòng về chất lượng dịch vụ cũng như các quyền lợi được cung cấp, và không muốn tiếp tục sử dụng dịch vụ của eDoctor, chúng tôi <strong>cam kết hoàn lại 100%</strong> số tiền quý khách hàng đã mua thẻ eDoctor.</p>
		</div>
		<div class="video">
			<h2 style="font-size:14px;"><i class="fa fa-comments"></i> Thạch sỹ, Bác sỹ Vũ Quốc Tuấn nói về dịch vụ tư vấn sức khỏe của eDoctor</h2>
			<iframe width="100%" height="315" src="//www.youtube.com/embed/MY0uOlZwXYo" frameborder="0" allowfullscreen></iframe> 
			<h2 style="font-size:14px;"><i class="fa fa-comments"></i> Bác sỹ Nguyễn Thị Thu Bích nói về dịch vụ tư vấn sức khỏe của eDoctor</h2>
			<iframe width="100%" height="315" src="//www.youtube.com/embed/tRpAUHL_jps" frameborder="0" allowfullscreen></iframe>
			<h2 style="font-size:14px;"><i class="fa fa-comments"></i> Bác sỹ Phạm Thị Lan chia sẻ về cách chăm sóc trẻ</h2>
			<iframe width="100%" height="315" src="//www.youtube.com/embed/Hexv307S3L0" frameborder="0" allowfullscreen></iframe>
		</div>
		<br />
	</div>
</div>