<p style="text-align: center;"><strong>HƯỚNG DẪN MUA THẺ VÀ THANH TOÁN</strong></p>

<p><strong>eDoctor</strong> kính chào quý khách, cảm ơn quý khách đã quan tâm đến dịch vụ của chúng tôi!</p>

<p>Để đăng ký và thanh toán phí mua thẻ, quý khách vui lòng thực hiện thực hiện theo các chỉ dẫn sau:</p>

<p><strong>B1.</strong> Chọn mệnh giá thẻ theo nhu cầu bằng cách click vào ô <strong>&ldquo;mua ngay&rdquo;</strong></p>

<p><strong>B2.</strong> Quý khách chọn số lượng thẻ muốn mua ở ô số lượng rồi click vào <strong>&ldquo;tiến h&agrave;nh thanh to&aacute;n&rdquo;</strong></p>

<p><strong>B3.</strong>Quý khách nhập địa chỉ email theo yêu cầu vào ô <strong> &ldquo;nhập v&agrave;o email&rdquo; </strong> sau đó click và <strong> &ldquo;tiếp tục&rdquo;</strong></p>

<p><strong>B4.</strong> Nhập các thông tin vào các trường yêu cầu</p>

<p><strong>B5.</strong> Chọn hình thức thanh toán</p>

<p>Quý khách có thể lựa chọn 1 trong 3 hình thức thanh toán là:</p>

<p><strong>- Thanh toán bằng tiền mặt khi nhận hàng</strong></p>

<p>Quý khách thanh toán tiền mặt cho nhân viên giao nhận (Giao hàng tận nơi) sau khi nhận được thẻ dịch vụ eDoctor</p>

<p><strong>- Chuyển khoản qua ngân hàng</strong></p>

<table border="0" cellpadding="0" style="width:580px">
	<tbody>
		<tr>
			<td colspan="3" style="height:23px">
			<p><strong><em>Quý khách vui lòng chuyển khoản đến một trong các tài khoản sau:</em></strong></p>
			</td>
		</tr>
		<tr>
			<td style="height:46px">
				<p><img alt="" src="http://edoctor.vn/layouts/default/img/Bank-Icons-01.jpg" style="height:38px; width:67px" /></p>
			</td>
			<td style="height:46px">
				<p> Ngân hàng thương mại cổ phần Ngoại thương Việt Nam - Vietcombank <br />
					Công ty Cổ phần E.D.O.C.T.O.R <br />
					STK: 002100301199
				</p>
			</td>
			<td style="height:46px">&nbsp;</td>
		</tr>
		<tr>
			<td style="height:46px">
			<p><img alt="Description: http://edoctor.vn/layouts/default/img/Bank-Icons-08.jpg" src="http://edoctor.vn/layouts/default/img/Bank-Icons-08.jpg" style="height:38px; width:67px" /></p>
			</td>
			<td style="height:46px">
				<p>	Ng&acirc;n h&agrave;ng Đ&ocirc;ng &Aacute;&nbsp;<br />
					STK: 01289465&nbsp;<br />
					Công ty Cổ phần E.D.O.C.T.O.R <br />
				</p>
			</td>
			<td style="height:46px">&nbsp;</td>
		</tr>
	</tbody>
</table>
<p><strong><em>Nội dung chuyển khoản, quý; khách vui lòng nhập theo mẫu</em></strong></p>
<p>&lt;Hovaten&gt; &ndash; &lt;Sodienthoai&gt; &ndash; &lt;Magiaodich&gt;</p>
<p><strong>Ví dụ: Nguyễn Văn A - 0906123456 - AE0724</strong></p>
<p><strong>Lưu ý:</strong> Sau khi chuyển tiền thành công, hệ thống của eDoctor sẽ tự động gửi mã số thẻ cho khách hàng thông qua hình thức tin nhắn và email.</strong></p>
<p>Mọi thông tin, yêu cầu, thắc mắc xin quý khách vui lòng liên hệ</p>
<p>&nbsp;</p>
<p><strong>Công ty Cổ phần eDoctor - 19006115</strong></p>
<p>Địa chỉ: Số 23, ngách 37/2, phố Dịch Vọng, Cầu Giấy, Hà Nội.</p>
<p>Hotline: <strong>0902.492.113</strong></p>
<p>Email: <a href="mailto:edoctor@edoctor.vn">edoctor@edoctor.vn</a></p>
<p>Website: http://edoctor.vn</p>
