<!--map-->
    <div id="map_canvas" class="map"></div>
    <!--/map-->
    <div class="row site"> 
        <!--Content-->
        <div style="margin-left:0;" class="col-md-11 side-bar" id="cont">
            <!--header-->
            <div class="row">
                <div class="col-md-12 header">
                    <div style="margin-left:0;" class="logo">
                        <a href="http://edoctor.vn">
                            <img src="/layouts/maps_maker/img/logo.png" /></a>
                    </div>
                </div>
            </div>
            <!--/header-->
            <!--tooltip-->
            <div class="jumbotron innerpage">
                <div class="container">
                    <h2 style="font-size:16px;">Đối tác của eDoctor</h2>
                </div>
            </div>
            <!--/tooltip-->
            <!--you can-->
            <div class="row">
                <div class="col-md-12 youcan">
                    <h4 style="font-size:13px;">Khi có thẻ eDoctor khách hàng sẽ:</h4>
                    <ul>
                        <li><span>1</span> Được giảm giá dịch vụ trên toàn bộ hệ thống đối tác</li>
                        <li><span>2</span> Được thăm khám sức khỏe tại nhà 2 lần/ năm</li>
                        <li><span>3</span> Được tiếp cận với các bệnh viện/ phòng khám uy tín dựa trên các tiêu chí riêng của eDoctor <br /> <br /> Và nhiều chương trình hấp dẫn khác..</li>
                    </ul>
                </div>
            </div>
            <!--/you can-->
            <!--where are you-->
            <div class="row">
                <div class="col-md-12 whereareyou">
                    <h4><strong>Mua thẻ eDoctor ở đâu?</strong></h4>
                    <i class="icon-shopping-cart"></i> <br /> 
                    <span><strong><i class="fa fa-shopping-cart"></i> Mua thẻ eDoctor trực tuyến!</strong></span>
                    <a style="margin-bottom:10px; width:100%;" href="http://edoctor.vn/dich-vu-tu-van-cham-soc-suc-khoe.htm?ref=KY7GD3GH" class="btn btn-danger btn-sm"><strong>MUA NGAY</strong></a> 
                    <br />
                    <span><strong><i class="fa fa-mobile"></i> Đặt mua qua điện thoại</strong></span> 
                    <a style="font-size:14px; margin-bottom:10px; width:100%;" href="tel:0466739922" class="btn btn-danger btn-sm" title=""><i style="font-size:14px;" class="fa fa-phone"></i> 0466 739 922</a> <br />
                    <a style="font-size:14px; margin-bottom:10px; width:100%;" href="tel:0903 492 113" class="btn btn-danger btn-sm" title=""><i style="font-size:14px;" class="fa fa-phone"></i> 0903 492 113</a> <br />
                    <span><i class="fa fa-map-marker"></i> <strong>Mua trực tiếp tại văn phòng!</strong></span>
                    <p>Công ty eDoctor, số 23, ngách 37/2 phố Dịch Vọng, Cầu Giấy, Hà Nội</p>
                </div>
            </div>
            <!--/where are you-->
            <!--You are here-->
            <div class="row">
                <div class="col-md-12">
                    <h4>Liên kết</h4>
                    <ul class="list-style-none">
                        <li><i class="fa fa-thumbs-up"></i> <a href="http://edoctor.vn/dich-vu-tu-van-cham-soc-suc-khoe.htm" title="">Thẻ eDoctor</a></li>
                        <li><i class="fa fa-thumbs-up"></i> <a href="http://edoctor.vn/dich-vu-tu-van-cham-soc-suc-khoe.htm" title="">Dịch vụ tư vấn sức khỏe</a></li>
                        <li><i class="fa fa-thumbs-up"></i> <a href="http://edoctor.vn/cham-soc-suc-khoe-ba-bau.htm" title="">Chăm sóc bà bầu</a></li>
                        <li><i class="fa fa-thumbs-up"></i> <a href="http://edoctor.vn/cham-soc-suc-khoe-ba-bau.htm" title="">cham soc ba bau</a></li>
                        <li><i class="fa fa-thumbs-up"></i> <a href="http://edoctor.vn/cham-soc-suc-khoe-ba-bau.htm" title="">suc khoe ba bau</a></li>
                    </ul>
                </div>
            </div>
            <!--/You are here-->
        </div>
        <!--/Content-->
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/layouts/maps_maker/js/bootstrap.js"></script>
    <!-- Google Tag Manager -->
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-NBDP5C"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-NBDP5C');</script>
    <!-- End Google Tag Manager -->