<?php $list = $this->list;?>
<div id="left-content">
	<div class="khuongnt_content likh full">
	<h1 style="margin-top:0 !important;" class="title-bg">Hướng dẫn sử dụng thẻ eDoctor</h1>
	<div class="note">
		<ul>
			<li><i class="fa fa-check"></i> Tư vấn kiến thức, kỹ năng cho phụ nữ mang thai và nuôi con nhỏ</li>
			<li><i class="fa fa-check"></i> Tư vấn chăm sóc sức khỏe; cách phòng chống, phát hiện và điều trị bệnh</li> 
			<li><i class="fa fa-check"></i> Tư vấn chế độ dinh dưỡng và sinh hoạt cho mọi lứa tuổi</li>
			<li><i class="fa fa-check"></i> Tư vấn giới tính, tâm lý – tình cảm</li>
			<li><i class="fa fa-check"></i> Tư vấn cách sử dụng các loại thuốc, thực phẩm chức năng</li>
			<li><i class="fa fa-check"></i> Tư vấn nơi khám bệnh trực tiếp có uy tín, giới thiệu bác sĩ điều trị giỏi</li>
			<li><i class="fa fa-check"></i> Tư vấn địa chỉ mua thuốc, dược phẩm có chất lượng</li>
		</ul>
	</div>
	<br />
	<a class="m-btn" href="tel:18006115" title=""><i class="fa fa-phone"></i> 18006115 (miễn phí)</a>
	<div class="note">
		Hãy dùng thử, mua và sử dụng thẻ eDoctor thường xuyên để giải quyết tất cả các vấn đến trên, và còn nhiều hơn thế nữa..
	</div>
	<div class="muathe">
		<a class="btn-cam" href="/mua-the.html" title="Mua thẻ eDoctor">Mua thẻ eDoctor</a>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
	<div class="full">
		<br />
		<h2><strong>1. Tôi có thể mua thẻ eDoctor ở đâu?</strong></h2>
	  	<p>Hiện tại thẻ eDoctor được phân phối tại các hiệu thuốc trên địa bàn Hà Nội hoặc gọi đến 1800 6115 nhánh số 0, số hotline 0903492113 và cung cấp địa chỉ để nhân viên giao thẻ tận nhà cho bạn.</p>
	  	<br />
	  	<h2><strong>2. Cách thức kích hoạt và nạp thẻ eDoctor như thế nào?</strong></h2>

	  	<div>
	  		<p>Cách 1: Gọi điện đến tổng đài 1800 6115 sau đó chọn phím 21 để nhập mã thẻ trên thẻ cào và nhấn phím # để hoàn tất dịch vụ.</p>
	  		<p>Cách 2: Gọi điện đến tổng đài 1800 6115 và chọn nhánh 0 gặp tổng đài viên.</p>
	  		<p>Cách 3: Nhắn tin theo cú pháp EKH [mã số thẻ] gửi 8009 (500đ/tin nhắn).</p>
	  	</div>
	  	<br />
	  	<h2><strong>3. Làm thế nào để thêm số điện thoại</strong></h2>
	  	<p>Một thẻ eDoctor có thể sử dụng cho 4 số điện thoại. Bạn có thể thêm số bằng cách gọi tới tổng đài 1800 6115 chọn nhánh 23 và làm theo hướng dẫn.</p>
	  	<br />
	  	<h2><strong>4. Làm thế nào để gặp đúng bác sĩ khi cần?</strong></h2>
	  	<p>Cách 1: Nếu đã biết rõ được bệnh của mình thì bạn có thể gọi đến tổng đài nhấn phím 1 và chọn chuyên khoa.</p>
	  	<p>Cách 2: Nếu chưa chắc chắn về bệnh của mình, bạn nên gọi đến 1800 6115 chọn nhánh 0 để được trợ giúp bởi Tổng Đài Viên.</p>
	  	<br />
	  	<h2><strong>5. Nếu chọn nhầm chuyên khoa tôi phải làm gì để gặp đúng bác sĩ?</strong></h2>
	  	<p>Nếu chọn nhầm chuyên khoa bạn nên gọi điện lại tổng đài 1800 6115 để được Tổng Đài Viên hỗ trợ 1 cách kịp thời nhất.</p>
	  	<br />
	  	<h2 id="hide_side"><strong>6. Làm thế nào để kết nối tới bác sĩ nhanh nhất ?</strong></h2>
	  	<p>Sau khi kết nối tới tổng đài, bạn có thể quay phím số nhanh bằng cách chọn luôn phím 1 và mã số chuyên khoa mình cần gặp.</p>
		<div class="note">
		Ví dụ: <br />
	   	<strong><i class="fa fa-caret-right"></i> 111</strong> để gặp bác sĩ Nội Khoa. <br />
	   	<strong><i class="fa fa-caret-right"></i> 112</strong> để gặp bác sĩ Ngoại khoa. <br />
	   	<span><i class="fa fa-arrow-circle-right"></i> Xem thêm: <a target="_blank" href="/huong-dan-goi-tu-van.htm" title=""><strong>Các phím tắt để gọi bác sĩ</strong></a></span>
		</div>
		<br />
	   	<h2><strong>7. Nếu có thắc mắc, phản ánh về dịch vụ tôi phải làm gì?</strong></h2>
	  	<p>Bạn có thể gọi điện trực tiếp đến 1800 6115 nhánh số 0 hoặc số hotline 0903492113 để giải đáp các thắc mắc và phản ánh chất lượng dịch vụ.</p>
	  	<br />
	  	<h2><strong>8. Có thể sử dụng dịch vụ eDoctor để thay thế việc khám bệnh được không?</strong></h2>
	  	<p>Có thể bạn chưa biết 78% các cuộc thăm khám bác sỹ có thể chỉ cần 1 cuộc điện thoại. Tuy nhiên để biết chính xác về bệnh tình của mình bạn nên gọi đến eDoctor để các bác sĩ đưa ra những lời khuyên hoặc các địa chỉ khám chữa bệnh uy tín nhất.</p>
	  	<br />
		<h2 style="color:#333; border-top:2px dashed #ddd; padding-top:10px; margin-top:10px;"><i class="fa fa-hand-o-right"></i> Các ưu đãi lớn từ hệ thống các đối tác của eDoctor:</h2>
		<div class="note">
			<p><i class="fa fa-thumbs-up"></i> Giảm giá từ 15% – 30% khi khám bệnh tại các bệnh viện và phòng khám eDoctor đang hợp tác (có danh sách kèm theo)</p>
			<p><i class="fa fa-thumbs-up"></i> Giảm giá khi chăm sóc sắc đẹp tại các thẩm mỹ viện, tập luyện ở các câu lạc bộ thể thao là đối tác của eDoctor</p>
			<p><i class="fa fa-thumbs-up"></i> Sử dụng dịch vụ tắm bé tại nhà với chi phí ưu đãi qua đối tác của eDoctor</p>
			<p><i class="fa fa-arrow-circle-right"></i> Xem thêm: <a target="_blank" href="/quyen-loi.htm" title=""><strong>Các đối tác của eDoctor</strong></a></p>
		</div>
		<div class="muathe">
			<a class="btn-cam" href="/mua-the.html" title="Mua thẻ eDoctor">Mua thẻ eDoctor</a>
			<div class="clear"></div>
		</div>
	</div>
</div>
</div>