<ul class="buckets">
	<li class="bucket">
		<h2 class="bucket-head"><a href="/dich-vu-tu-van-cham-soc-suc-khoe.htm">Thẻ eDoctor</a></h2>
		<div class="content">
			<span class="sub-head">Hoàn tiền 100% nếu bạn không hài lòng với dịch vụ của eDoctor trong 30 ngày đầu tiên.</span>
			<a href="/dich-vu-tu-van-cham-soc-suc-khoe.htm"><img alt="tu van cham soc suc khoe" src="/upload/images/the-tu-van-cham-soc-suc-khoe-edoctor.jpg"></a>
			<p>
				Sử dụng dịch vụ tư vấn, chăm sóc sức khỏe qua tổng đài <strong>18006115</strong> của eDoctor khách hàng sẽ nhận được những lời khuyên hữu ích của bác sỹ. 
				Được tiếp cận với các dịch vụ y tế hàng đầu và được giảm phí dịch vụ tại các bệnh viện, phòng khám.. là đối tác của eDoctor. Hãy đảm bảo cho gia đình bạn luôn khỏe mạnh với thẻ eDoctor!
			</p>
		</div>
	</li>
	<li class="bucket bucket2">
		<h2 class="bucket-head"><a href="/bac-sy-edoctor.htm">Đội ngũ bác sỹ eDoctor</a></h2>
		<div class="content">
			<span class="sub-head">Đội ngũ hơn 350 giáo sư, bác sỹ đã và đang làm việc tại các bệnh viện lớn trên toàn quốc.</span>
			<a href="/bac-sy-edoctor.htm"><img alt="bac si tu van cham soc suc khoe" src="/upload/images/doi-ngu-bac-si.jpg"></a>
			<p>
				Đội ngũ bác sỹ tư vấn chăm sóc sức khỏe của eDoctor đang không ngừng tăng lên mỗi ngày để đáp ứng lại sự quan tâm của quý khách hàng đã dành cho eDoctor.
				Các giáo sư, tiến sỹ, bác sỹ giàu kinh nghiệm thuộc tất cả các chuyên khoa <strong>luôn sẵn sàng</strong> nghe điện thoại và  đưa ra những tư vấn, lời khuyên cho bạn bất cứ lúc nào!
			</p>
		</div>
	</li>
	
	<li class="bucket">
		<h2 class="bucket-head"><a href="/loi-ich-cua-khach-hang.htm">Lợi ích của thẻ eDoctor</a></h2>
		<div class="content">
			<span class="sub-head">Với thẻ eDoctor, đội ngũ bác sỹ hàng đầu.. eDoctor đem lại nhiều giá trị cho người sử dụng.</span>
			<a href="/loi-ich-cua-khach-hang.htm"><img alt="tu van suc khoe" src="/upload/images/loi-ich-the-tu-van-cham-soc-suc-khoe-edoctor.jpg"></a>
			<p>
				Với mong muốn giúp khách hàng tiết kiệm thời gian khám chữa bệnh, thu hẹp khoảng cách giữa người bệnh và bác sỹ, nâng cao kiến thức về y tế, chăm sóc sức khỏe cho mỗi người, mỗi gia đình. <strong>Không thủ tục rườm rà - Không phải chờ đợi lâu - Kết nối 24/24</strong>, thẻ eDoctor đã và đang ngày càng khẳng định giá trị to lớn đem lại cho người sử dụng.  
			</p>
		</div>
		<br />
		<a class="btn-cam" href="/mua-the.html" title="Mua thẻ eDoctor">Mua thẻ eDoctor</a>
	</li>
</ul>
<div class="clear"></div>
<div class="full" id="testimonials">
	<div class="padding">
		<h2>Khách hàng nói về eDoctor</h2>
		<div class="full" id="list-testimonials">
			<ul class="bxslider">
				<li>
					<div class="test-item">
						<div class="test-content">
							<p>Đây là lần đầu tiên mình sử dụng dịch vụ tư vấn sức khỏe của eDoctor, mới đầu thì cũng không quen lắm vì từ trước không có thói quen gọi điện hỏi bác sĩ mà cứ ốm đau là mình đến viện khám luôn. Nhưng gọi vài lần thấy quen dần bởi các bác sĩ tư vấn rất nhiệt tình, mình áp dụng theo chỉ dẫn của bác sĩ thấy rất hiệu quả. Giờ gia đình mình có ai bị ốm đau gì nhẹ là gọi điện đến eDoctor gặp bác sĩ tư vấn nên ít khi phải đi viện khám, tiết kiệm được rất nhiều thời gian và tiền nữa. Chúc eDoctor ngày càng phát triển!</p>	
						</div>
						<div class="test-info">
							<img src="/layouts/default/img/cus1.png" alt="">
							<p>
							<strong>Chị Ngọc Diệp</strong>
							<span>Hà Đông, Hà Nội</span>
							</p>
						</div>
					</div>
				</li>
				<li>
					<div class="test-item">
						<div class="test-content">
							<p>Mình đang mang bầu em bé thứ 2 nhưng về các kỹ năng chăm sóc sức khỏe bà bầu và nhất là chăm bé mình còn thiếu nhiều lắm, mấy hôm lang thang trên diễn đàn thấy các Mẹ nói nhiều về dịch vụ eDoctor có thể giúp các mẹ có thêm kiến thức chăm sóc bé nên mình mua liền. Mình gọi thì được gặp các bác sĩ tư vấn, trời, rất tuyệt, bác sĩ tư vấn rất nhiệt tình, hơn thế còn được giảm giá khi đi mua đồ trẻ em, đi spa nữa. Mình đã bảo các chị gái của mình và họ cũng đã dùng và đánh giá rất tốt.</p>	
						</div>
						<div class="test-info">
							<img src="/layouts/default/img/cus2.png" alt="">
							<p>
							<strong>Chị Hồng Vân</strong>
							<span> (Cầu Giấy, Hà Nội)</span>
							</p>
						</div>
					</div>
				</li>
			</ul>
	        <div class="clear"></div>
		</div>
	</div>
</div>