<?php $list = $this->list;?>
<div id="left-content">
	<div class="khuongnt_content likh full">
	<h1 style="margin-top:0 !important;" class="title-bg">Khách hàng doanh nghiệp và tổ chức</h1>
	<br />
	<h2><strong><i class="fa fa-hand-o-right"></i> Khách hàng doanh nghiệp và tổ chức</strong></h2>
	<p>Con người là tài sản vô giá của doanh nghiệp và tổ chức. Ngoài chế độ lương thưởng và các chính sách phúc lợi truyền thống như bảo hiểm, đào tạo, khám sức khỏe định kì,… các doanh nghiệp, tổ chức không ngừng tìm kiếm những giải pháp mới để chăm sóc một cách tốt nhất đến sức khỏe và tinh thần của người lao động.</p>
	<p>Dựa trên nền tảng công nghệ telehealthcare hiện đại, eDoctor hân hạnh mang tới Quý Doanh nghiệp, Tổ chức 1 giải pháp chăm sóc cả về thể chất & tinh thần cho nhân viên 24/24 một cách hữu hiệu và kinh tế nhất.</p>
	<br />
	<h3><strong>Các lợi ích chính eDoctor đem lại cho Doanh nghiệp:</strong></h3>
	<div>
		<ul>
			<li>Một giải pháp phúc lợi nhân viên kinh tế nhất nhưng được sử dụng tối đa nhất (24h/ngày và 365 ngày/năm)</li>
			<li>Một công cụ hữu hiệu để thu hút và giữ chân nhân tài</li>
			<li>Đảm bảo thể chất và tinh thần của nhân viên 24/24, từ đó tăng hiệu quả lao động</li>
			<li>Tiết kiệm chi phí: tiết kiệm chi phí y tế, bảo hiểm,đi lại,... của nhân viên và công ty</li>
			<li>Chăm sóc tốt hơn đến cá nhân và gia đình người lao động</li>
			<li>Giảm tần suất vắng mặt và tăng tần suất giờ làm của người lao động</li>
			<li>Nâng cao hình ảnh, vị thế công ty</li>
		</ul>
	</div>
	<p>Còn chờ gì nữa, hãy mang đến cho nhân viên những chương trình phúc lợi tuyệt vời để khích lệ tinh thần làm việc hăng say. Hãy cho nhân viên viên đăng ký dùng thử để trải nghiệm dịch vụ trước khi ra quyết định mua thẻ eDoctor (miễn phí sử dụng suốt 24h đầu)</p>
	<br />
	<h2 id="hide_side"><strong><i class="fa fa-hand-o-right"></i> Bảo hiểm</strong></h2>
	<p>Với đối tác là nhà bảo hiểm hay tư vấn bảo hiểm, chúng tôi hân hạnh giới thiệu eDoctor như một dịch vụ giá trị gia tăng cho khách hàng doanh nghiệp hay cá nhân của bảo hiểm, góp phần nâng cao lợi thế cạnh tranh, tăng thêm sự hài lòng cho khách hàng với chi phí hợp lý.</p>
	<br />
	<h3><strong>Các lợi ích chính của Bảo hiểm khi kết hợp với eDoctor:</strong></h3>
	<div>
		<ul>
			<li>Nâng cao chất lượng Dịch vụ với eDoctor: Không khấu trừ, không phải ra khỏi nhà, không phải hẹn khám. Tiết kiệm thời gian, tiền bạc và công sức</li>
			<li>Tăng cường năng lực cạnh tranh của sản phẩm bảo hiểm, từ đó tăng doanh thu.</li>
			<li>Tiết kiệm chi phí đi lại, khám chữa bệnh cho khách hàng, từ đó giảm chi phí bồi thường bảo hiểm (đặc biệt là ngoại trú)</li>
			<li>Nâng cao hiệu quả quản lý và khai thác bảo hiểm: hạ tỷ lệ tổn thất; có cơ sở dữ liệu khách hàng theo bệnh và tần suất khám chữa; nâng cao nhận thức khách hàng và giữ khách hàng “xa” bệnh viện.</li>
			<li>Tạo điều kiện cho khách hàng tiếp cận với đội ngũ bác sỹ hàng đầu trên toàn quốc và đảm bảo cho khách hàng được chăm sóc tư vấn về y tế và sức khỏe 24/7/365</li>
			<li>Tăng mức độ hài lòng của khách hàng & Nâng cao hình ảnh, vị thế công ty</li>
		</ul>
	</div>
	<br />
	<h2><i class="fa fa-hand-o-right"></i> <strong>Đối tác khác</strong></h2>
	<div>
		<p>Quý Công ty có thể là ngân hàng đang tìm kiếm giải pháp để chăm sóc cho các khách hàng thẻ tín dụng Vàng hay Kim Cương. Quý công ty là công ty lữ hành mong muốn chăm sóc tốt nhất cho du khách của mình trong mỗi chuyến đi. Hay Quý công ty có thể là nhà mạng viễn thông, hãng hàng không, hãng xe…đang mong muốn những giải pháp mới để nâng cao sự hài lòng của khách hàng…. Hãy liên hệ với chúng tôi, eDoctor – Chăm sóc sức khỏe toàn diện 24/7 là 1 dịch vụ giá trị gia tăng tuyệt vời quý công ty có thể sử dụng để chăm sóc cho khách hàng của mình.</p>
	</div>

	<div>
		<p>Bạn muốn trở thành đối tác phân phối của eDoctor? Bạn đang có 1 hiệu thuốc và muốn thêm sản phẩm mới vào quầy hàng của bạn? Bạn là trường mầm non muốn giới thiệu eDoctor tới bố mẹ các em học sinh để các con được chăm sóc sức khỏe tốt hơn? Hãy liên hệ ngay với chúng tôi để trở thành nhà phân phối dịch vụ eDoctor với nhiều quyền lợi ưu đãi.</p>
	</div>
	<div class="muathe">
		<a class="btn-cam" href="/mua-the.html" title="Mua thẻ eDoctor">Mua thẻ eDoctor</a>
		<div class="clear"></div>
	</div>
	<br />
	<div style="text-align:justify;" class="thumbs-up">
		<p>Hãy gọi ngay <strong>18006115</strong> để miễn phí dùng thử dịch vụ tư vấn, chăm sóc sức khỏe của eDoctor trong 24h đầu. Hoặc mua thẻ eDoctor với chính sách <strong>hoàn lại 100% giá trị</strong> thẻ nếu khách hàng không muốn tiếp tục sử dụng dịch vụ của eDoctor trong <strong>30 ngày đầu tiên</strong>.</p>
	</div>
	<br />
	<a class="m-btn" href="tel:18006115" title=""><i class="fa fa-phone"></i> 18006115 (miễn phí)</a>
	<br />
</div>
</div>