<?php $list = $this->list;?>
<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,500,700&subset=latin,vietnamese' rel='stylesheet' type='text/css'>
<div id="priceTable" class="clear">
	<div class="the_content">
		<h1><strong>Thẻ chăm sóc sức khỏe eDoctor</strong></h1>
		<h2><i class="fa fa-hand-o-right"></i> <strong>Ưu điểm của dịch vụ tư vấn chăm sóc sức khỏe với thẻ eDoctor</strong></h2>
		<p style="font-size: 15px;">
			<img alt="" src="http://edoctor.vn/layouts/default/img/s.jpg" width="18" style="margin-bottom: 5px;">ử dụng dịch vụ thẻ tư vấn, chăm sóc sức khỏe của eDoctor quý khách không phải đi lại tốn kém, xếp hàng mệt mỏi, vất vả tìm phòng khám có uy tín tìm bác sĩ đúng chuyên ngành có kinh nghiệm... mà vẫn có được thông tin tư vấn cần thiết. Với 15 chuyên khoa sâu đi vào từ vấn đề cụ thể trong y học, eDoctor như một bệnh viện mini thu nhỏ bỏ túi cho mỗi gia đình có trẻ nhỏ, người cao tuổi, người mắc các bệnh mãn tính và phụ nữ trong độ tuổi đang có dấu hiệu thay đổi nội tiết tố có nguy cơ phát sinh nhiều vấn đề sức khỏe
		</p>
		<div style="width:100%;text-align: center;">
			<ul class="list-featured">
				<li>
					<div class="iconfe">
						<i class="fa fa-check fa-5x"></i>
					</div>
					<span>Tiện lợi</span>
					<p>Chỉ cần nhấc điện thoại và gọi 18006115 (miễn phí cước gọi) cũng được gặp ngay các bác sĩ chuyên khoa mà không cần phải đến bệnh viện</p>
				</li>
				<li>
					<div class="iconfe">
						<i class="fa fa-clock-o fa-5x"></i>
					</div>
					<span>Tiết kiệm thời gian</span>
					<p>Những thắc mắc về sức khỏe sẽ được đội ngũ bác sĩ của eDoctor trả lời sau vài giây kết nối thay vì việc phải xếp hàng tại bệnh viện.</p>
				</li>
				<li>
					<div class="iconfe">
						<i class="fa fa-medkit fa-5x"></i>
					</div>
					<span>Hữu ích</span>
					<p>Dễ dàng sử dụng và thuận tiện cho gia đình có trẻ em, người cao tuổi, người có tiểu sử mắc các bệnh mãn tính, đồng bào vùng sâu vùng xa</p>
				</li>
				<li>
					<div class="iconfe">
						<i class="fa fa-thumbs-o-up fa-5x"></i>
					</div>
					<span>Chất lượng</span>
					<p>Đội ngũ bác sĩ tư vấn của eDoctor 100% là các bác sĩ trên 10 năm kinh nghiệm đã và đang công tác tại các viện lớn của Hà Nội</p>
				</li>
			</ul>
		</div>
		<h2><i class="fa fa-hand-o-right"></i> <strong>Đội ngũ bác sĩ tham gia tư vấn chăm sóc sức khỏe của eDoctor</strong></h2>
		<p style="font-size: 15px;">
		<img alt="" src="http://edoctor.vn/layouts/default/img/l.jpg" width="18" style="margin-bottom: 5px;">à các giáo sư, tiến sĩ, bác sĩ có bằng cấp được đào tạo bài bản, có kinh nghiệm chuyên sâu đã và đang công tác tại các bệnh viện lớn trên toàn quốc. Đó là các bác sĩ giàu lòng nhân ái, mong muốn cống hiến cho xã hội trong lĩnh vực chăm sóc sức khoẻ. Tất cả vì một xã hội lành mạnh, không có bệnh tật.</p>
		<p style="text-align:center;">Chỉ cần gọi về <i style="color:#0088cc" class="fa fa-phone fa-lg"></i> Tổng đài <a style="font-size:16px;" href="tel:18006115"><strong>18006115</strong></a> <span style="color:#999; font-size:12px;">(miễn phí cước gọi)</span> - hàng trăm bác sĩ đang chờ điện thoại của bạn.</p>
		<br />
		<ul class="list-doctor">
			<li>
				<div class="img-doctor">
					<img title="GSTS Dương Trọng Hiếu" src="http://edoctor.vn/layouts/default/img/bac-si-tu-van-suc-khoe-duong-trong-hieu.jpg" alt="bac si tu van cham soc suc khoe edoctor">
				</div>
				<h3>GSTS Dương Trọng Hiếu</h3>
				<span>Bác sĩ chuyên khoa II y học cổ truyền</span>
			</li>
			<li>
				<div class="img-doctor">
					<img title="PGSTS Tô Văn Hải" src="http://edoctor.vn/layouts/default/img/bac-si-tu-van-suc-khoe-to-van-hai.jpg" alt="bac si tu van cham soc suc khoe">
				</div>
				<h3>PGSTS Tô Văn Hải</h3>
				<span>Bác sĩ chuyên khoa nhi cấp II</span>
			</li>
			<li>
				<div class="img-doctor">
					<img title="PGSTS Nguyễn Thị Ngọc Dinh" alt="bac si tu van suc khoe" src="http://edoctor.vn/layouts/default/img/bac-si-tu-van-suc-khoe-nguyen-thi-ngoc-dinh.jpg">
				</div>
				<h3>PGSTS Nguyễn Thị Ngọc Dinh</h3>
				<span>Thầy thuốc chuyên khoa tai, mũi, họng</span>
			</li>
		</ul>
		<h2><i class="fa fa-hand-o-right"></i> <strong>Những quyền lợi khi sở hữu thẻ chăm sóc sức khỏe eDoctor</strong></h2>
		<ul style="line-height:20px;">
			<li><i class="fa fa-check-square"></i> Nhận được những <a href="http://edoctor.vn/dich-vu-tu-van-suc-khoe.htm"><strong>tư vấn chăm sóc sức khỏe</strong></a>, tư vấn làm đẹp từ trên 350 giáo sư, bác sĩ trên toàn quốc.</li>
			<li><i class="fa fa-check-square"></i> Bất cứ thời gian nào, ngày nào... chỉ cần gọi điện về <strong>18006115</strong> khách hàng sẽ nhận được sự tư vấn của các bác sĩ</li>
			<li><i class="fa fa-check-square"></i> Nhận được các ưu đãi, giảm giá với <a target="_blank" href="/quyen-loi/" title=""><strong>hệ thống đối tác của eDoctor</strong></a> 
				<ul>
					<li><i class="fa fa-check"></i> Khám chữ bệnh tại các bệnh viện, phòng khám</li>
					<li><i class="fa fa-check"></i> Chăm sóc y tế tại nhà</li>
					<li><i class="fa fa-check"></i> Làm đẹp tại các trung tâm thẩm mỹ, Spa và Fitness</li>
				</ul>
			</li>
			<li><i class="fa fa-check-square"></i> Được thăm, khám chữ bệnh tại nhà mỗi năm 2 lần (nếu khách hàng có nhu cầu)</li>
			<li><i class="fa fa-check-square"></i> Được tham gia, sử dụng các sản phẩm, phần mềm chăm sóc sức khỏe với những tính năng hiện đại, cung cấp nhiều kinh nghiệm bổ ích về kiến thức chăm sóc sức khỏe cho mọi nhà.</li>
			<li><i class="fa fa-check-square"></i> Trong vòng 30 ngày đầu mua thẻ eDoctor, khách hàng có quyền trả lại thẻ và được <strong>hoàn trả 100% tiền</strong> nếu cảm thấy không hài lòng với dịch vụ của eDoctor.</li>
		</ul>
	</div>
	<div id="the-edoctor" class="price-table">
		<div class="book-online">
		<h2>Đặt mua thẻ chăm sóc sức khỏe eDoctor trực tuyến</h2>
		<p style="text-align:left;">Hiện tại eDoctor đang cung cấp 01 loại thẻ duy nhất, có thời hạn sử dụng là 01 năm. Quý khách hàng có thể tùy chọn số lượng thẻ cần mua, hãy <a target="_blank" href="/lien-he.htm" title="">liên hệ với eDoctor</a> để biết thêm thông tin. 
		</p>
		</div>
		<p>
			<img src="http://edoctor.vn/upload/images/the-cham-soc-suc-khoe-edoctor1.jpg" alt="tu van cham soc suc khoe edoctor">
		</p>
		<?php 
		if($list):
			foreach ($list AS  $item):
			if($item->code =='YEARLY_BILLING'):
		?>
			<a href="javascript://" style="width:140px; margin:20px auto;" class="buy_now btn-flat"  onclick="openThickbox('<?php echo $item->id?>', 1)">Mua ngay</a>
		<?php 
			endif;
			endforeach;	
		endif;?>
	</div>
	<!--end table-->
	<div class="the_content">
		<div class="note">
			<i style="color:red;" class="fa fa-hand-o-right"></i> Với chính sách dùng thử 24h đầu tiên cho mỗi số điện thoại. Ngay từ bây giờ bạn có thể gọi đến đầu số <strong>18006115</strong> (miễn phí cước gọi) để dùng thử và trải nghiệm dịch vụ tư vấn, chăm sóc sức khỏe của eDoctor. <br>
			<i style="color:red;" class="fa fa-hand-o-right"></i> eDoctor đang có chương trình mua và dùng thẻ eDoctor, <strong>trong vòng 30 ngày</strong>.. nếu quý khách hàng cảm thấy không hài lòng và không muốn tiếp tục sử dụng dịch vụ của eDoctor. Khách hàng có thể trả lại thẻ, <strong>eDodoctor hoàn trả 100% số tiền mua thẻ cho khách hàng</strong>.
		</div>
		<div class="note">
			<p><strong>Thẻ chăm sóc sức khỏe eDoctor</strong> đã có mặt ở hầu hết các hiệu thuốc trên toàn quốc, ngay bây giờ bạn có thể tìm mua thẻ chăm sóc sức khỏe eDoctor tại các cửa hàng thuốc gần nhất hoặc bạn có thể mua trực tiếp tại trên website.</p>
			<p><i class="fa fa-credit-card"></i> <b>Hướng dẫn mua thẻ chăm sóc sức khỏe eDoctor trực tiếp trên website <a rel="nofollow" target="_blank" href="http://edoctor.vn/huong-dan-mua-the-truc-tuyen.htm">tại đây.</a></b></p>
			<p><i class="fa fa-phone fa-lg"></i> <b>Hướng dẫn gọi bác sĩ tư vấn về sức khỏe <a rel="nofollow" target="_blank" href="http://edoctor.vn/huong-dan-goi-tu-van.htm">tại đây.</a></b></p>
			<p><i class="fa fa-pencil"></i> <b>Hướng dẫn sử dụng dịch vụ tư vấn/ thẻ chăm sóc sức khỏe eDoctor <a rel="nofollow" target="_blank" href="http://edoctor.vn/cach-su-dung-dich-vu.htm">tại đây.</a></b></p>
		</div>
	</div>
	<!--end note-->
	<div class="buy-by-phone">
		<h3>Đặt mua thẻ chăm sóc sức khỏe eDoctor qua điện thoại:</h3>
		<p><i class="fa fa-phone fa-lg"></i> Điện thoại: <a href="tel:046 6739 922"><strong>046 6739 922</strong></a> - <i class="fa fa-phone fa-lg"></i> Hotline: <a href="tel:0903492113"><strong>0903492113</strong></a></p>
	</div>
</div>
<div class="mua-ngay"><a href="#the-edoctor" class="btn-flat" title="Mua thẻ eDoctor"><i class="fa fa-hand-o-right"></i> Mua ngay</a></div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
function openThickbox(code, qty) {
	var url = "/cart/show-cart?KeepThis=true&TB_iframe=true&width=650&height=350";
	 $.ajax({
        url: '/cart/new',
		type: "POST",
        data: {'qty': qty, 'code':code},
        success:function(){
        	tb_show("", url);
		},
    });
};

$(document).ready(function() {
	 $(".mua-ngay a").click(function (){
          //$(this).animate(function(){
              var value = $(this).attr("href");
              $('html, body').animate({
                  scrollTop: $(value).offset().top
              }, 500);
          //});
      return false;
      });
	 /*end js khuongnt*/
});

function popup() {
	window.open("/huong-dan-mua-the.htm",'Hướng dẫn mua thẻ eDoctor','width=640,height=500,resizable=yes,scrollbars=yes,top=100,left=200');
}
</script>
<style>
#listProduct {display: none;}
ul.reason {
	float: left;
}	
li, ol, ul {
list-style: none;
}
ul.reason li {
	float: left;
	width: 232px;
	margin-right: 10px;
	padding-top: 145px;
	text-align: center;
}	
</style>