<?php $list = $this->list;?>
<div id="left-content">
	<div class="khuongnt_content likh full">
	<h1 style="margin-top:0 !important;" class="title-bg">Lợi ích của chủ sở hữu thẻ eDoctor</h1>
	<br />
	<p>Đối với doanh nghiệp việc theo dõi sức khỏe thường xuyên mang lại “lợi ích ghép” cho cả doanh nghiệp và người lao động. Còn với mọi người dân thì đó giống như là nhu cầu cần thiết trong cuộc sống. Sử dụng dịch vụ <a href="http://edoctor.vn/dich-vu-tu-van-cham-soc-suc-khoe.htm" title=""><strong>tư vấn sức khỏe</strong></a> thường xuyên giúp cho mọi người biết được tình trạng sức khỏe của mình, phát hiện sớm các bệnh lý, bệnh nghề nghiệp, mang lại hiệu quả điều trị và nâng cao chất lượng cuộc sống. Đồng thời, đơn vị, doanh nghiệp sẽ nắm bắt được tình trạng sức khỏe người lao động, nâng cao hiệu quả công việc và góp phần tạo sự phát triển bền vững đơn vị.</p>
	<br />
	<h2><i class="fa fa-hand-o-right"></i> Tư vấn, hướng dẫn chăm sóc sức khỏe Miễn Phí 24/24 từ các bác sĩ:</h2>
	<a class="m-btn" href="tel:18006115" title=""><i class="fa fa-phone"></i> 18006115 (miễn phí)</a>
	<div class="note">
		<p><i class="fa fa-star"></i> Hướng dẫn chăm sóc sức khỏe miễn phí 24/24 từ các bác sĩ nhiều năm kinh nghiệm làm việc trong các chuyên khoa qua số điện thoại <strong>18006115</strong></p>
		<p><i class="fa fa-star"></i> Được trải nghiệm chất lượng dịch vụ của eDoctor trong chương trình miễn phí tư vấn 24h đầu qua đầu số <strong>18006115</strong> trước khi quyết định mua thẻ eDoctor</p>
		<p><i class="fa fa-star"></i> <strong>Hoàn trả lại tiền cho khách hàng sau 30 ngày sử dụng nếu không hài lòng về chất lượng dịch vụ</strong></p>
		<p><i class="fa fa-star"></i> Được thăm khám sức khỏe hàng tháng qua điện thoại</p>
	</div>
	<br />
	<h2><i class="fa fa-hand-o-right"></i> Được hưởng các ưu đãi lớn từ hệ thống các đối tác của eDoctor như:</h2>
	<div class="thumbs-up">
		<p><i class="fa fa-thumbs-up"></i> Giảm giá từ 15% – 30% khi khám bệnh tại các bệnh viện và phòng khám eDoctor đang hợp tác (có danh sách kèm theo)</p>
		<p><i class="fa fa-thumbs-up"></i> Giảm giá khi chăm sóc sắc đẹp tại các thẩm mỹ viện, tập luyện ở các câu lạc bộ thể thao là đối tác của eDoctor</p>
		<p><i class="fa fa-thumbs-up"></i> Sử dụng dịch vụ tắm bé tại nhà với chi phí ưu đãi qua đối tác của eDoctor</p>
		<p><i class="fa fa-arrow-circle-right"></i> Xem thêm: <a target="_blank" href="/quyen-loi.htm" title=""><strong>Các đối tác của eDoctor</strong></a></p>
	</div>
	<div class="muathe">
		<a class="btn-cam" href="/mua-the.html" title="Mua thẻ eDoctor">Mua thẻ eDoctor</a>
		<div class="clear"></div>
	</div>
	<br />
	<h2 id="hide_side"><i class="fa fa-hand-o-right"></i> Lợi ích đối với Doanh nghiệp và người lao động</h2>
	<h3><i class="fa fa-arrow-circle-right"></i> Lợi ích của doanh nghiệp</h3>
	<div class="note">
	<p><i class="fa fa-check"></i> Giảm được các chi phí y tế, chi phí bồi thường cho người lao động mắc bệnh</p>
	<p><i class="fa fa-check"></i> Bảo vệ và phát triển lực lượng sản xuất, tạo sự gắn bó của người lao động với doanh nghiệp, nâng cao năng xuất lao động, giảm tai nạn lao động, bệnh nghề nghiệp.</p>
	<p><i class="fa fa-check"></i> Tạo dựng uy tín, chất lượng thương hiệu, tăng sức cạnh tranh của sản phẩm, tạo sự phát triển bền vững cho doanh nghiệp.</p>
	</div>
	<br />
	<h3><i class="fa fa-arrow-circle-right"></i> Lợi ích của người lao động</h3>
	<div class="note">
		<p><i class="fa fa-check"></i> Phát hiện được các vấn đề về sức khỏe trước khi chuyển thành bệnh, nhất là các bệnh không có các biểu hiện ra bên ngoài.</p>
		<p><i class="fa fa-check"></i> Tạo điệu kiện thuận lợi cho việc điều trị có hiệu quả cao, giảm chi phí y tế.</p>
		<p><i class="fa fa-check"></i> Nâng cao chất lượng cuộc sống, kéo dài tuổi thọ.</p>
		<p><i class="fa fa-check"></i> Sử dụng dịch vụ tư vấn sức khỏe ngay hôm nay để được chăm sóc, bảo vệ sức khỏe mỗi ngày và hưởng những ưu đãi lớn từ eDoctor.
	Đăng ký mua thẻ ngay tại đây.</p>
	</div>
	<div class="muathe">
		<a class="btn-cam" href="/mua-the.html" title="Mua thẻ eDoctor">Mua thẻ eDoctor</a>
		<div class="clear"></div>
	</div>
	<br /> 
</div>
</div>