<?php 
$row = $this->row;
$listNewsLQ = $this->listNewsLQ ;
?>
<!-- <h2 id="page-title"> -->
<?php //echo $row->news_name?>
<!-- </h2> -->
<!-- ARTICLE -->
<div id="article" class="curvyRedraw">
	<div class="padding">
		<p><strong><?php echo $row->news_name?></strong></p>
		<hr style="margin: -10px 0 20px 0px;"></hr>
		<p><b><?php echo $row->news_intro?></b></p>
		<?php echo $row->news_desc?>
		<table style="border: 1px soild #ddd;">
			<tr>
				<td width="285" style="padding: 0 10px 0px; line-height: 20px;">
					<span style="text-align: left;">Thích và chia sẻ bài viết này trên:</span>
					<br/>
					<iframe src="//www.facebook.com/plugins/like.php?href=<?php echo Luong_Helper_Utils::curPageURL()?>&amp;width=150&amp;layout=button_count&amp;action=like&amp;show_faces=true&amp;share=true&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:150px; height:21px;" allowTransparency="true"></iframe>
					<div class="g-plusone" data-size="medium"></div>
				</td>
				<td width="285"> 
					<span style="text-align: left;">Theo dõi <b>eDoctor.vn</b> qua FB, G+:</span>
					<br/>
					<iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fedoctorvn%3Fref%3Dprofile&amp;width=150&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;share=true&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:150px; height:21px;" allowTransparency="true"></iframe>
 				</td> 
			</tr>
		</table>
		<div class="fb-comments" data-href="<?php echo Luong_Helper_Utils::curPageURL()?>" data-width="570" data-numposts="3" data-colorscheme="light"></div>
		<p><strong>Tin khác</strong></p>
		<ul>
		<?php 
		if($listNewsLQ):
			foreach ($listNewsLQ AS $item):
			$l = '/tin-tuc/t'.$item->news_id.'-'.Luong_Helper_Utils::cv2urltitle($item->news_name).'.htm';
		?>
			<li><a href="<?php echo $l?>" class="help"><?php echo $item->news_name?></a></li>
		<?php 
			endforeach;
		endif;
		?>
		</ul>
	</div>
</div>
<!-- END ARTICLE -->
<!-- SIDEBAR --> 
<div id="sidebar">
	<?php echo $this->render('ads.phtml');?>
	<?php echo $this->render('news.phtml');?>
    <?php echo $this->render('right.phtml');?>
</div>
<!-- END SIDEBAR --> 