<?php 
$list 	= $this->list;
$cat    = $this->cat;
?>
<h2 id="page-title"><?php echo $article->art_name?></h2>
<!-- ARTICLE -->
<div id="article" class="curvyRedraw">
	<div id="padding">
		<p>
		<div class="widget-title">
			<?php Echo $cat->cat_name?>
		</div>
		</p>
		<?php foreach ($list AS $val):
			$link = '/tin-tuc/t'.$val->news_id.'-'.$val->news_seo.'.htm';
		?>
		<div class="newsItem">
			<div class="imgItem">
				<a href="<?php echo $link ?>"><img src="<?php echo $val->news_image?>" width="158" height="100"/></a>
			</div>
			<div class="descItem">
				<a class="help" href="<?php echo $link ?>"><?php echo $val->news_name?></a>
				<div class="intro"><?php echo Luong_Helper_Utils::substr(strip_tags($val->news_desc), 200) ?></div>
				<div class="more"><a href="<?php echo $link?>">chi tiết</a></div>
			</div>
		</div>
		<?php endforeach;?>
	</div>
	<div>
		<div class="pagingDiv"><?php //echo $this->page_title ?><?php echo $this->page?></div>
	</div>
</div>
<!-- END ARTICLE -->
<!-- SIDEBAR --> 
<div id="sidebar">
	<?php echo $this->render('ads.phtml');?>
	<?php echo $this->render('catnews.phtml');?>
	<?php Echo $this->render('news.phtml')?>
    <?php echo $this->render('right.phtml');?>
</div>
<!-- END SIDEBAR --> 