<?php if(isset($this->qaAnser['qa_name'])): ?>
	<h1 class="full" id="page-title"><strong>Thắc mắc sức khoẻ của <?php echo $this->qaAnser['qa_name']; ?></strong></h1>
	<div class="clear"></div>
	</div><!--end rwidth head post-->
</div>
<!--end head post-->
<div class="padding">
	<div class="khuongnt_content services full">
		<div class="rwidth">
			<div class="col col700 the_content">
				 <div class="qa_quest full">
                	<h2 style="margin-top:0;"><i class="fa fa-question-circle"></i> Bạn <?php echo $this->qaAnser['qa_name']; ?> hỏi</h2>
                	<?php 
                	if(isset($this->qaAnser['qa_phone'])):
                	$phone = str_replace(substr($this->qaAnser['qa_phone'], -4, 4), '****', $this->qaAnser['qa_phone']); 
                	endif;
                	?>
                	<span class="qa_meta"><?php if($phone) { ?>SĐT: <?php echo $phone; ?> - <?php } ?><?php echo date("d-m-Y H:i", $this->qaAnser['qa_time']); ?></span>
                    <div class="content_quest full">
                    	<p><?php echo $this->qaAnser['qa_content'];?></p>
                    	<a class="more_quest" href="#" title="">Xem thêm <i class="fa fa-chevron-down"></i></a>
                    </div>
                    <div class="qa_answer full"> 
	                	<div class="content-answer">
	                		<h4><i class="fa fa-comments-o"></i> Trả lời từ bác sỹ eDoctor</h4>
	                		<div class="container_answer">
	                			<?php echo $this->qaAnser['qa_answer'];?>
	                		</div>
	                		<a class="more_answer" href="#" title="">Xem thêm <i class="fa fa-chevron-down"></i></a>
	                	</div>
	                </div>
	                <div style="margin-top:20px;" class="full">
						<div class="success">
							<a href="/gui-cau-hoi.html" title=""><i class="fa fa-check-circle-o"></i> Gửi câu hỏi</a>
						</div>
						<div class="success">
							<a href="/giai-dap-thac-mac-suc-khoe.html" title=""><i class="fa fa-check-circle-o"></i> Thắc mắc sức khoẻ đã có câu trả lời từ bác sỹ eDoctor</a>
						</div>
						<div class="warning2">
							<a href="/thac-mac-suc-khoe-cho-tra-loi.html" title=""><i class="fa fa-clock-o"></i> Thắc mắc sức khoẻ đang chờ bác sỹ eDoctor trả lời</a>
						</div>
					</div>

                </div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="clear"></div>
	</div>
</div>
</article>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$('.content_quest > p').each(function() {
			if($(this).height() > 120) {
				$(this).css('height', '120px');
			} else {
				$(this).next('a').hide();
			}
		});
		$('.container_answer').each(function() {
			if($(this).height() > 135) {
				$(this).css('height', '135px');
			} else {
				$(this).next('a').hide();
			}
		});
		$('.more_quest').click(function() {
			if($(this).hasClass('active')) {
				$(this).prev('p').css('height', '120px');
				$(this).removeClass('active');
				$(this).html('Xem thêm <i class="fa fa-chevron-down"></i>')
			} else {
				$(this).prev('p').css('height', 'auto');
				$(this).addClass('active');
				$(this).html('Thu gọn <i class="fa fa-chevron-up"></i>');
			}
			return false;
		});
		$('.more_answer').click(function() {
			if($(this).hasClass('active')) {
				$(this).prev('div').css('height', '140px');
				$(this).removeClass('active');
				$(this).html('Xem thêm <i class="fa fa-chevron-down"></i>')
			} else {
				$(this).prev('div').css('height', 'auto');
				$(this).addClass('active');
				$(this).html('Thu gọn <i class="fa fa-chevron-up"></i>');
			}
			return false;
		});
	});
</script>
<?php else: 
$URL = '/gui-cau-hoi.html';
header('Location: '.$URL);
endif; ?>