<?php $list = $this->list;?>
<style type="text/css" media="screen">
	.content-partner {min-height: 94px;}
</style>
<div id="banner-quyenloi">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1 class="element_from_left">Quyền lợi của khách hàng</h1>
						<p>Khi sử dụng dịch vụ tư vấn, <a style="color:#FFF;" href="http://edoctor.vn/dich-vu-tu-van-suc-khoe.htm"><strong style="font-weight:400;">chăm sóc sức khỏe</strong></a> - thẻ eDoctor</p>
					</div>
				</div>
			</div>
		</div>
		<!-- Services -->
		<div id="quyen-loi">
			<div class="container">
				<div class="row list-benhvien">
					<h2>Các ưu đãi lớn từ hệ thống đối tác của eDoctor</h2>
					<div class="col-md-8">
						<div class="thumbs-up">
							<p><i class="fa fa-thumbs-up"></i> Giảm giá từ 15% – 30% khi khám bệnh tại các bệnh viện và phòng khám eDoctor đang hợp tác (có danh sách kèm theo)</p>
							<p><i class="fa fa-thumbs-up"></i> Giảm giá khi chăm sóc sắc đẹp tại các thẩm mỹ viện, tập luyện ở các câu lạc bộ thể thao là đối tác của eDoctor</p>
							<p><i class="fa fa-thumbs-up"></i> Sử dụng dịch vụ tắm bé tại nhà với chi phí ưu đãi qua đối tác của eDoctor</p>
							<p><i class="fa fa-arrow-circle-right"></i> Xem thêm: <a target="_blank" href="/cac-doi-tac-tai-ha-noi-cua-edoctor.htm" title=""><strong>Các đối tác tại Hà Nội của eDoctor</strong></a> trên Google Maps</p>
						</div>
						<div style="margin-top:10px;" class="thumbs-up">
							<p><i class="fa fa-hand-o-right"></i> <strong>Hoàn lại 100%</strong> giá trị thẻ nếu khách hàng không hài lòng và không muốn tiếp tục sử dụng dịch vụ của eDoctor trong 30 ngày đầu tiên. Hãy gọi ngay <strong>18006115</strong> để MIỄN PHÍ dùng thử dịch vụ tư vấn, chăm sóc sức khỏe của eDoctor trong 24h đầu.</p>
						</div>
					</div>
					<div class="col-md-4">
						<div class="thumbs-up thumbs_side">
							<p><i class="fa fa-hand-o-right"></i> <strong>365 ngày có bác sỹ tư vấn sức khỏe</strong></p>
							<p><i class="fa fa-hand-o-right"></i> <strong>Thăm khám sức khỏe mỗi tháng 1 lần qua điện thoại</strong></p>
							<div style="margin-top:10px;" class="muathe">
								<a href="http://edoctor.vn/onepage.htm" style="display:block; margin:0 auto; text-align:center;" class="buy_now btn-cam">
									<i class="fa fa-shopping-cart"></i> Mua thẻ eDoctor
								</a>
								<div class="clear"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Services end -->
	    <?php if(isset($list)):?>
		<!-- Portfolio -->
		<section id="portfolio" class="content">
	        <!-- Container -->
			<div class="container portfolio-title">
				
	            <!-- Section Title -->
	            <div class="section-title">
	                <h2>Hệ thống các đối tác của eDoctor</h2>
	                <span class="border"></span>
	                <p>Quý khách hàng là chủ sở hữu thẻ eDoctor sẽ được hưởng nhiều chế độ ưu đãi khi sử dụng dịch vụ của hệ thống đối tác</p>
	            </div>				
				<!--/Section Title -->
	        </div> 
	        <!-- Container -->  
	        <div class="portfolio-top"></div>          
	        
	              
	        <!-- Portfolio Plus Filters -->
	        <div class="portfolio">
	        
	       <!-- Portfolio Filters -->   
	       <div  id="filters" class="sixteen columns">
	        
	          <ul class="clearfix">
	            <li><a id="all" href="#" data-filter="*" class="active"><h5>Tất cả</h5></a></li>
	            <?php foreach ($list AS $item):?>
	            <li><a href="#" data-filter=".group<?php echo $item->catId?>"><h5><?php echo $item->catName?></h5></a></li>
	            <?php endforeach;?>
	          </ul>
	        </div>
	        <!--/Portfolio Filters -->
	        <!-- Portfolio Wrap -->  
	        <div id="portfolio-wrap">
	            <?php foreach ($list AS $item):?>
	                <?php foreach ($item->item AS $v):?>
	                <?php //var_dump($v) ?>
	                <!-- Partner Item --> 
	                <div style="background:url(<?php echo $v->image?>) no-repeat center center" class="portfolio-item one-four <?php if($v->id == 10) echo 'group7' ?> group<?php echo $item->catId;?>">
	                	<h2 style="text-align:center; font-size:16px; padding-top:40px;"><strong><a href="/doi-tac/<?php echo $v->alias; ?>.html" title=""><?php echo $v->name; ?></a></strong></h2>
	                    <div style="visibility:hidden;" class="portfolio-image">
	                        <img src="/layouts/responsive/img/portfolio/portfolio2.jpg" alt="Portfolio"/> 
	                    </div>
	                    <a title="<?php echo $v->name; ?>" href="/doi-tac/<?php echo $v->alias; ?>.html">
	                    <div class="project-overlay">              
	                        <div class="project-info">
	                            <div class="zoom-icon"></div>
	                            <p class="project-categories"><strong><i class="fa fa-map-marker"></i> <?php echo $v->address; ?></strong></p>   
	                        </div>
	                    </div>
	                    </a>
	                </div>    
	                <!--/Partner Item  -->    
	                <?php endforeach;?>    
	            <?php endforeach;?>
	        </div>
	        <!--/Portfolio Wrap -->
	        </div>
	        <!--/Portfolio Plus Filters -->
	        <div class="portfolio-bottom"></div>
	        <!-- Project Page Holder-->
	        <div id="project-page-holder">
	            
	            <div class="clear"></div>
	            <div id="project-page-data"></div>
	        
	        </div>
	        <!--/Project Page Holder-->  
		</section>	
		<!--/Portfolio -->
		<?php endif;?>
		<!-- Purchase -->
		<div class="purchase">
			<div class="container">
				<div class="row">
					<div class="col-md-9">
						<p><i class="fa fa-hand-o-right"></i> Mua thẻ <a style="color:#FFF;" href="http://edoctor.vn/the-cham-soc-suc-khoe-edoctor.htm">chăm sóc sức khỏe</a> eDoctor ngay hôm này để được hưởng các chương trình ưu đãi<br />
						<span>Chỉ cần gọi về Tổng đài 18006115 (miễn phí cước gọi) - hàng trăm bác sĩ là các Giáo sư, tiến sĩ… đang chờ điện thoại của bạn.</span></p>
					</div>
					<div class="col-md-3 purchase-button element_from_right">
						<a href="http://edoctor.vn/onepage.htm" title="Thẻ chăm sóc sức khỏe eDoctor" class="btn btn-default btn-green">Mua online</a>
					</div>
				</div>
			</div>
		</div>
		<!-- Purchase end -->