<?php $list = $this->list;?>
<h2 id="page-title"><strong>Thẻ eDoctor</strong></h2>
<div class="khuongnt_content services full">
	<div class="full">
		<div>
			<h1>Dịch vụ tư vấn, chăm sóc sức khỏe - thẻ eDoctor</h1>
			<p><i class="fa fa-share"></i> Thẻ eDoctor mang đến cho khách hàng dịch vụ tư vấn và chăm sóc sức khỏe toàn diện với các ưu điểm nổi bật như tiết kiệm thời gian, công sức, nhanh chóng kết nối bác sĩ và các dịch vụ y tế để đáp ứng các nhu cầu chăm sóc bảo vệ sức khỏe.</p>
			<div class="muathe">
				<a class="btn-cam" href="/mua-the.html" title="Mua thẻ eDoctor">Mua thẻ eDoctor</a>
			</div>
		</div>
	</div>
	<div class="full">
		<iframe width="100%" height="315" style="border-radius:3px;" src="//www.youtube.com/embed/tRpAUHL_jps" frameborder="0" allowfullscreen></iframe>
	</div>
	
	<h2 class="title-bg full"><strong>Thẻ tư vấn, chăm sóc sức khỏe eDoctor bao gồm các dịch vụ</strong></h2>
	<div class="full">
		<div >
			<h3><strong><i class="fa fa-hand-o-right"></i>Hoàn toàn miễn phí gọi Bác sỹ hướng dẫn chăm sóc sức khỏe 24/24 qua số điện thoại 18006115:</strong></h3>
			<strong >Đội ngũ hơn 350 bác sỹ luôn sẵn sàng 24/24</strong> <br />
			<div class="clear"></div>
			<ul class="note">
				<li><i class="fa fa-check"></i> Tư vấn kiến thức, kỹ năng cho phụ nữ mang thai và nuôi con nhỏ</li>
				<li><i class="fa fa-check"></i> Tư vấn chăm sóc sức khỏe; cách phòng chống, phát hiện và điều trị bệnh</li> 
				<li><i class="fa fa-check"></i> Tư vấn chế độ dinh dưỡng và sinh hoạt cho mọi lứa tuổi</li>
				<li><i class="fa fa-check"></i> Tư vấn giới tính, tâm lý – tình cảm</li>
				<li><i class="fa fa-check"></i> Tư vấn cách sử dụng các loại thuốc, thực phẩm chức năng</li>
				<li><i class="fa fa-check"></i> Tư vấn nơi khám bệnh trực tiếp có uy tín, giới thiệu bác sĩ điều trị giỏi</li>
				<li><i class="fa fa-check"></i> Tư vấn địa chỉ mua thuốc, dược phẩm có chất lượng</li>
			</ul>
		</div>
	</div>
	<div class="clear"></div>
	<div class="full">
		<h3><strong><i class="fa fa-hand-o-right"></i>Thăm khám sức khỏe hàng tháng qua điện thoại</strong></h3>
		<p class="answer"><strong class="content-answer">Hãy đến Với dịch vụ thăm khám sức khỏe định kỳ của eDoctor qua điện thoại, bạn sẽ được chăm sóc tận tình ít nhất 1 lần/tháng, chúng tôi sẽ lưu lại các thông tin về sức khỏe để hỗ trợ khách hàng chăm sóc bản thân, đối phó với bệnh dịch và theo dõi sự tiến triển của quá trình điều trị.</strong></p>
	</div>
	<div class="clear"></div>
	<h3><strong>Ngoài các dịch vụ trên, khách hàng sở hữu thẻ eDoctor còn được hưởng các quyền lợi như:</strong></h3>
	<p>Được cung cấp tài khoản theo dõi sử dụng dịch vụ eDoctor, nghe lại các nội dung tư vấn của bác sĩ và cập nhật thông tin về tình hình sức khỏe trên website, trên ứng dụng điện thoại di động.</p>
	<p><strong>Nhận được các ưu đãi giảm giá đặc biệt khi sử dụng dịch vụ trong hệ thống các đối tác eDoctor:</strong></p>
	<div class="full">
		<div class="answer">
			<ul class="note">
				<li><i class="fa fa-long-arrow-right"></i> Khám chữa bệnh tại các bệnh viện, phòng khám</li>
				<li><i class="fa fa-long-arrow-right"></i> Chăm sóc sức khỏe tại nhà</li>
	 			<li><i class="fa fa-long-arrow-right"></i> Tập luyện, điều trị tại các spa – trung tâm Fitness</li>
	 			<li><i class="fa fa-long-arrow-right"></i> Các chương trình hội thảo, huấn luyện về chăm sóc sức khỏe, bảo vệ sức khỏe</li>
	 			<li><i class="fa fa-long-arrow-right"></i> Thông tin về quyền lợi của chủ thẻ eDoctor được liên tục cập nhật tại đường link edoctor.vn/quyen-loi</li>
			</ul>
		</div>
	</div>
	<div class="clear"></div>
	<h2 style="margin-top:20px;" class="full"><strong>Chi phí và hướng dẫn sử dụng</strong></h2>
	<div class="full chiphi">
		<h3><strong><i class="fa fa-credit-card"></i> Chi phí dịch vụ - cam kết hoàn lại 100% nếu không hài lòng về dịch vụ.</strong></h3>
		<div class="dash_border full">
			<p><strong>Miễn phí dùng thử dịch vụ</strong>  - trong 24h kể từ lần đầu tiên sử dụng dịch vụ, quý khách hàng sẽ không phải trả bất kỳ khoản phí nào để sử dụng dịch vụ bác sĩ tư vấn của eDoctor. Trong thời gian này khách hàng sẽ được trải nghiệm đầy đủ và sâu sắc về dịch vụ bác sĩ tư vấn khám chữa bệnh không giới hạn số lần và thời gian thực hiện.</p>
			<br />
			<a class="m-btn" href="tel:18006115" title=""><i class="fa fa-phone"></i> 18006115 (miễn phí)</a>
			<br />
			<p>Để sử dụng dịch vụ đầy đủ sau 24h đầu tiên, quý khách hàng sẽ <strong>mua Thẻ eDoctor có giá trị 990.000 VND</strong>, có thời gian sử dụng trong <strong>12 tháng kể từ ngày kích hoạt thẻ</strong>. Với thẻ dịch vụ eDoctor khách hàng được sử dụng toàn bộ các dịch vụ chính và các quyền lợi để được chăm sóc sức khỏe một cách toàn diện và chất lượng. Tổng đài <strong>18006115</strong> kết nối giữa bạn với bác sĩ 24/24 và cước gọi đối với chủ sở hữu thẻ eDoctor về tổng đài là <strong>Miễn Phí</strong></p>

			<p>Trong thời gian 30 ngày kể từ ngày kích hoạt thẻ eDoctor, nếu quý khách hàng không hài lòng về chất lượng dịch vụ cũng như các quyền lợi được cung cấp, và không muốn tiếp tục sử dụng dịch vụ của eDoctor, chúng tôi <strong>cam kết hoàn lại 100% </strong> số tiền quý khách hàng đã mua thẻ eDoctor.</p>
			<div class="muathe full">
				<a class="btn-cam" href="/mua-the.html" title="Mua thẻ eDoctor">Mua thẻ eDoctor</a>
			</div>
		</div>
	</div>
	<div class="full huongdan">
		<h3><strong><i class="fa fa-book"></i> Cách sử dụng dịch vụ:</strong></h3>
		<p>Kích hoạt thẻ dịch vụ: với thao tác soạn tin nhắn <strong>EKH dấu cách mã PIN gửi đến 8009</strong>; hoặc gọi đến <strong>18006115</strong> (hoàn toàn miễn phí cước gọi) và làm theo hướng dẫn, quý khách sẽ dễ dàng kích hoạt thẻ eDoctor và chính thức bắt đầu trải nghiệm dịch vụ tư vấn chăm sóc sức khỏe toàn diện của eDoctor.</p>
		<p>Để nhanh chóng kết nối đến các bác sĩ tư vấn, quý khách vui lòng sử dụng các phím tắt sau ngay sau khi bấm điện thoại gọi đến <strong>18006115</strong> (hoặc đơn giản nhấn 0 để được trợ giúp):</p>
		<br />
		<a class="m-btn" href="tel:18006115" title=""><i class="fa fa-phone"></i> 18006115 (miễn phí)</a>
		<br />
		<p><strong>Gọi trực tiếp bác sĩ theo từng khoa</strong></p>
		<br />
		<a href="tel:18006115,1,11" class="call-button"><i class="fa fa-phone"></i> 11 Gặp trực tiếp bác sĩ Sản khoa</a>
		<a href="tel:18006115,1,12" class="call-button"><i class="fa fa-phone"></i> 12 Gặp trực tiếp bác sĩ Nhi khoa</a>
		<a href="tel:18006115,1,13" class="call-button"><i class="fa fa-phone"></i> 13 Gặp trực tiếp bác sĩ Nội khoa - Hồi sức cấp cứu</a>
		<a href="tel:18006115,1,14" class="call-button"><i class="fa fa-phone"></i> 14 Gặp trực tiếp bác sĩ Ngoại khoa</a>
		<a href="tel:18006115,1,15" class="call-button"><i class="fa fa-phone"></i> 15 Gặp trực tiếp bác sĩ Mắt</a>
		<a href="tel:18006115,1,16" class="call-button"><i class="fa fa-phone"></i> 16 Gặp trực tiếp bác sĩ Răng hàm mặt</a>
		<a href="tel:18006115,1,17" class="call-button"><i class="fa fa-phone"></i> 17 Gặp trực tiếp bác sĩ Tai mũi họng</a>
		<a href="tel:18006115,1,18" class="call-button"><i class="fa fa-phone"></i> 18 Gặp trực tiếp bác sĩ Y học cổ truyền</a>	
		<a href="tel:18006115,1,19" class="call-button"><i class="fa fa-phone"></i> 19 Gặp trực tiếp bác sĩ Tâm lý</a>		
	</div>
	<div class="clear"></div>
	<div class="full">
		<div class="book_card">
			<div class="padding">
				<h2><strong>Đặt mua thẻ eDoctor trực tuyến (giao thẻ tận nhà)</strong></h2>
					<a class="btn-cam" href="/mua-the.html" title="Mua thẻ eDoctor">Mua thẻ eDoctor</a>
				</div>
			</div>
		</div>
	</div>
</div>