<?php $id = $this->id?>
<div class="form-inline" id="<?php echo $id?>">
	<div class="row">
		<div class="form-group has-feedback col-md-4">
			<label class="sr-only" for="item_serial_<?php echo $id?>_type">Loại thẻ</label> 
			<select class="form-control item_serial_type" name="item[<?php echo $id?>][chuyenkhoa_id]">
				<option value="0">Chuyên Khoa</option>
				<?php foreach ($this->medical_specialty_list AS $item):?>
					<option value="<?php echo $item->id?>"><?php echo $item->name?></option>
				<?php endforeach;?>
			</select>
		</div>
		<div class="form-group has-feedback col-md-4">
			<input type="text" class="form-control item_tenbenh" placeholder="Tên bệnh" name="item[<?php echo $id?>][tenbenh]">
		</div>
	</div>
	<div class="row">
		<div class="form-group has-feedback col-md-4">
			<input type="text" class="form-control item_thoigianmac" placeholder="Thời gian mắc" name="item[<?php echo $id?>][thoigianmac]">
		</div>
		<div class="form-group has-feedback col-md-4">
			<input type="text" class="form-control item_noidieutri" placeholder="Nơi điều trị" name="item[<?php echo $id?>][noidieutri]">
		</div>
		<div class="form-group has-feedback col-md-4">
			<input type="text" class="form-control item_thoigiandieutri" placeholder="Thời gian điều trị" name="item[<?php echo $id?>][thoigiandieutri]">
		</div>
	</div>
	<div class="row">
		<div class="form-group has-feedback col-md-6">
			<textarea placeholder="Biểu hiện lâm sàng" name="item[<?php echo $id?>][bieuhienlamsang]"></textarea>
		</div>
		<div class="form-group has-feedback col-md-6">
			<textarea placeholder="Các xét nghiệm" name="item[<?php echo $id?>][cacxetnghiem]"></textarea>
		</div>
	</div>
	<div class="row">
		<div class="form-group has-feedback col-md-6">
			<textarea placeholder="Chuẩn đoán hình ảnh" name="item[<?php echo $id?>][chuandoanhinhanh]"></textarea>
		</div>
		<div class="form-group has-feedback col-md-6">
			<textarea placeholder="Thuốc điều trị" name="item[<?php echo $id?>][thuocdieutri]" id="content"></textarea>
		</div>
	</div>
	<div class="form-group">
		<button type="button" class="btn btn-circle btn-danger removeItemList" title="Hủy dải thẻ này">-</button>
	</div>
</div>