<?php $listAddress = $this->listAddress; ?>
<div class="old-dress full">
    <?php
    if (!empty($listAddress)):
        $count = 0;
        foreach ($listAddress AS $itemA):
            $count++;
            ?>
            <div class="block-item <?php if ($count % 2 == 0) echo 'right0'; ?>">
                <p class="name-ship"><b><i class="fa fa-user"></i> <?php echo $itemA->fullname ?></b></p>
                <p class="address-ship"><i class="fa fa-map-marker fa-lg"></i> <?php echo $itemA->address ?>, <?php echo $itemA->district_name ?>, <?php echo $itemA->province_name ?></p>
                <p class="phone-ship"><a href="tel:<?php echo $itemA->mobile ?>" title=""><i class="fa fa-phone-square"></i> <?php echo $itemA->mobile ?></a></p>
                <p class="mgt10">
                    <span class="add-ship btn-cam" onclick="address('<?php echo $itemA->id ?>')"><i class="fa fa-check-square-o"></i> Giao đến địa chỉ này</span>
                </p>
            </div>
            <?php
        endforeach;
    endif;
    ?>
</div>
<div class="title-address mg">
    <b>Bạn muốn giao hàng đến địa chỉ khác? <a class="new-address__click" href="javascript:void(0)" rel="1">Thêm địa chỉ giao hàng mới</a></b>
</div>
<?php
$errors = $this->errors;
$list = $this->list;
$listProvince = $this->listProvince;
$listDistrict = $this->listDistrict;
?>
<div class ="box_new_address" <?php
if ($errors)
    echo 'style="display: block"';
else
    echo 'style="display: none"';
?>>
    <form class="form-horizontal" action="" method="POST">
        <div class="control-group">
            <label class="control-label">Họ tên:</label>
            <div class="controls">
                <input type="text" id="fullname" placeholder="Họ và tên" name="fullname" value="<?php if ($this->fullname) echo $this->fullname ?>" class="span4">
                <?php if ($errors->fullname_error): ?>
                    <span class="help-block has-error"><?php echo $errors->fullname_error ?></span>
                <?php endif; ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Số điện thoại:</label>
            <div class="controls">
                <input type="text" id="mobile" placeholder="Số điện thoại" name="mobile" value="<?php if ($this->mobile) echo $this->mobile ?>" class="span4">
                <?php if ($errors->mobile_error): ?>
                    <span class="help-block has-error"><?php echo $errors->mobile_error ?></span>
                <?php endif; ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Email:</label>
            <div class="controls">
                <input type="text" id="mobile" placeholder="Địa chỉ email" name="email" value="<?php if ($this->email) echo $this->email ?>" class="span4">
                <?php if ($errors->email_error): ?>
                    <span class="help-block has-error"><?php echo $errors->email_error ?></span>
                <?php endif; ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Tỉnh/thành phố:</label>
            <div class="controls">
                <select name="province" class="span4" id="province">
                    <option value="0">Vui lòng chọn Tỉnh/Thành phố</option>
                    <?php foreach ($listProvince AS $item): ?>
                        <option value="<?php echo $item->id ?>" <?php if ($this->province == $item->id) echo 'selected="selected"' ?>><?php echo $item->name ?></option>
                    <?php endforeach; ?>
                </select>
                <?php if ($errors->province_error): ?>
                    <span class="help-block has-error"><?php echo $errors->province_error ?></span>
                <?php endif; ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Quận/Huyện:</label>
            <div class="controls" id="district">
                <select name="district" class="span4">
                    <option value="0">Vui lòng chọn Quận/Huyện</option>
                    <?php if ($listDistrict): ?>
                        <?php foreach ($listDistrict AS $item): ?>
                            <option value="<?php echo $item->id ?>" <?php if ($this->district == $item->id) echo 'selected="selected"' ?>><?php echo $item->name ?></option>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </select>
                <?php if ($errors->district_error): ?>
                    <span class="help-block has-error"><?php echo $errors->district_error ?></span>
                <?php endif; ?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Địa chỉ:</label>
            <div class="controls">
                <textarea rows="" cols="" name="address" class="span4"><?php echo $this->address ?></textarea>
                <?php if ($errors->address_error): ?>
                    <span class="help-block has-error"><?php echo $errors->address_error ?></span>
                <?php endif; ?>
            </div>
        </div>

        <div class="control-group">
            <div class="controls">
                <button style="padding:0 18px;" type="submit" class="btn-flat" id="step2"><i class="fa fa-check-square-o"></i> Thêm địa chỉ</button>
            </div>
        </div>
    </form>
</div>
<style>
    .mg {
        margin:30px auto;
    }
    .mg2 {
        margin: 20px auto 10px;
    }
    .title-address {
        width: 100%;
        float:left;
        font-size: 16px !important;
        height: 30px;
        line-height: 30px;
    }

    .title-address a {
        color: #4f79ba;
        font-size: 16px;
    }
    .default-address {
        line-height: 20px;
        margin-bottom: 30px;
    }
    .block-address{
        width: 100%;
        margin: 10px auto;
        border-top: 1px solid #ccc;
    }
    .block-item {
        width: 49%;
        margin-right: 2%;
        float: left;
        margin-top: 20px;
        line-height: 20px;
    }
    .mgt10{
        margin-top: 10px;
    }
    .old-dress {padding-bottom: 20px; border-bottom: 1px solid #ddd;}
</style>