<div class="widget did-you-know cycle cycle-diy">
    <h4 class="widget-title-cart">Địa chỉ giao thẻ eDoctor</h4>
    <div class="order_cart info-user" style="min-height: 70px;">
        <ul>
            <li>Họ tên: <strong><?php echo $_SESSION['info']['fullname']; ?></strong></li>
            <li>Địa chỉ: <strong><?php echo $_SESSION['info']['address']; ?>, <?php echo $_SESSION['info']['district_name']; ?>, <?php echo $_SESSION['info']['province_name']; ?></strong></li>
            <li>Số điện thoại: <strong><?php echo $_SESSION['info']['mobile']; ?></strong></li>
            <li><a href="/twopage.htm" class="btn-edit"><i class="fa fa-pencil-square-o"></i> Thay đổi thông tin giao thẻ</a></li>
        </ul>
    </div>
</div>