<div class="panelContainer">
    <h2 class="panelHeader"><span>THÊM MỚI</span></h2>
    <div class="panelWrapper">
        <div class="panelContent">
            <form name="frm" method="post" class="form_field" enctype="multipart/form-data">
                <div class="blockContent">
                    <fieldset>
                        <dl class="formRow">
                            <dt>
                            <label for="resumeTitle">Danh mục: <span class="required">*</span></label>
                            </dt>
                            <dd class="formValue">
                                <input type="text" class="text w50" name="name" id="name" value="" required="required"/>			
                            </dd>
                        </dl>
                        <dl class="formRow">
                            <dt>
                            <label for="resumeTitle">Thứ tự <span class="required">*</span></label>
                            </dt>
                            <dd class="formValue">
                                <input type="text" class="text w50" name="order" id="order" value="" required="required" maxlength="7"/>
                            </dd>   
                        </dl>

                        <dl class="formRow">
                            <dt>
                            <label for="resumeTitle">Image (200x150): <span class="required">*</span></label>
                            </dt>
                            <dd class="formValue">
                                <input type="file" name="file" id="image_file"/>
                                <div id="show_image"> </div>	
                            </dd>
                        </dl>

                        <center>
                            <button type="submit" name="Submit" onclick='check()' class="btn btn-primary"><span>Thêm</span></button>
                            <a onclick='javascript:window.location = "<?php echo $this->contextPath ?>"'  class="btn btn-primary" style="text-decoration: none;"><span>Quay lại</span></a>
                        </center>
                    </fieldset>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        var forder = '/upload/category';
        $('#image_file').uploadify({
            'formData': {
                'folder': forder,
                'fileext': 'png|gif|jpg|jpeg|bmp|JPG|PNG|GIF|JPEG|BMP',
            },
            'fileSizeLimit': 10000,
            'fileTypeExts': '*.png; *.gif; *.jpg; *jpeg; *.bmp;*.JPG;*.GIF;*.JPEG,*.PNG,*.BMP',
            'swf': '/layouts/admin/js/uploadify/uploadify.swf',
            'uploader': '/admin/category/upload',
            'cancelImg': '/layouts/admin/js/uploadify/uploadify-cancel.png',
            'multi': false,
            'onUploadSuccess': function(file, data) {
                var response_code = data.substring(0, 1);
                var file_name = data.substring(2);
                var data = forder + '/' + file_name;
                if (response_code == 0) {
                    $("#popup-content").html(file_name);
                    $("#show-popup").click();
                } else {
                    show_image(data);
                }
            }
        });
    });
    function show_image(data) {
        var img = "<input name = 'image' value = '" + data + "' type='hidden'>" + '<img src="' + data + '" style="width: 200px;"/>';
        $("#show_image").html(img);
    }
</script>