<?php
$list = $this->list;
?>
<div class="table table-list">
    <?php if ($this->success) : ?>
        <div class="notification success">
            <span class="strong"></span>
            <?php echo $this->success ?>
            <span class="close" title="Dismiss"></span>
        </div>
    <?php endif; ?>
    <div id="jtable_wrapper" class="dataTables_wrapper" role="grid">
        <div class="fg-toolbar ui-toolbar ui-widget-header ui-corner-tl ui-corner-tr ui-helper-clearfix">
            <div>
                <label>
                    <a class="btnadd" style="text-decoration: none;" href="<?php echo $this->contextPath; ?>/add">
                        <img src="/layouts/admin/icons/add.png"/> Thêm mới
                    </a>
                </label>
            </div>
        </div>
        <table cellpadding="0" cellspacing="0" border="3" class="display dataTable" id="jtable" aria-describedby="jtable_info">
            <thead>
                <tr>
                    <th class="w5">STT</th>
                    <th>Tên</th>
                    <th>Link</th>
                    <th class="w10">Thứ tự</th>
                    <th class="w10">Thời gian</th>
                    <th class="w10 align-center">Action</th>
                </tr>
            </thead>
            <tbody role="alert" aria-live="polite" aria-relevant="all">
                <?php
                if ($list):
                    $i = 1;
                    foreach ($list AS $item) :
                        $link = '/c' . $item->id . '-' . Luong_Helper_Utils::cv2urltitle($item->name) . '.htm';
                        ?>
                        <tr class="<?php
                        if ($i % 2 == 1)
                            echo 'odd';
                        else
                            echo 'even'
                            ?>" >
                            <td class="align-center sorting_1"><?php echo $i ?></td>
                            <td><?php echo $item->name ?></td>
                            <td><a target="_blank" href="<?php echo $link ?>"><?php echo $link ?></a></td>
                            <td><input onchange="change('<?php echo $item->id ?>')" id="order<?php echo $item->id ?>" value="<?php echo $item->order ?>" size="1" style="text-align: right;" rel="<?php echo $item->id ?>"/></td>
                            <td><?php echo $item->date ?></td>
                            <td class="action align-center">
                                <a href="<?php echo $this->contextPath ?>/edit?id=<?php echo $item->id; ?>">
                                    <img alt='edit' src='/layouts/admin/icons/edit.png' /> 
                                </a>
                                &nbsp;
                                <a rel='<?php echo $this->contextPath ?>/delete?id=<?php echo $item->id ?>' class="btnDeleteRow" href="javascript://">
                                    <img alt='delete' src='/layouts/admin/icons/delete.png'/>
                                </a>
                            </td>
                        </tr>
                        <?php
                        $i++;
                    endforeach;
                    ?>
                <?php endif; ?>
            </tbody>
        </table>
        <div class="fg-toolbar ui-toolbar ui-widget-header ui-corner-bl ui-corner-br ui-helper-clearfix">
            <?php echo $this->page_title ?>
            <?php echo $this->page; ?>
        </div>
    </div>
</div>