<?php $options = $this->options; ?>
<?php if ($this->success) : ?>
    <div class="alert alert-success fade in">
        <button data-dismiss="alert" class="close" type="button">×</button>
        <strong>Well done! </strong> <?php echo $this->success ?>.
    </div>
<?php endif; ?>
<div class="row">
    <div class="span12">
        <div class="widget-block">
            <div class="widget-head">
                <h5> Form ELements</h5>
            </div>
            <div class="widget-content">
                <div class="widget-box">
                    <form class="form-horizontal well white-box" method="post" action="" enctype="multipart/form-data">
                        <fieldset>
                            <div class="control-group">
                                <label class="control-label" for="input501">SITE NAME</label>
                                <div class="controls">
                                    <input type="text" class="span9" id="input501" name="site_name" value="<?php echo $options['title'] ?>" title="Tiều đề của trang website"/>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="input502">META TITLE</label>
                                <div class="controls">
                                    <input type="text" class="span9" id="input5021" name="meta_title" value="<?php echo $options['meta_title'] ?>"/>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">META DESCRIPTION</label>
                                <div class="controls">
                                    <textarea class="span9" name="description"><?php echo $options['description'] ?></textarea>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Google Analytics</label>
                                <div class="controls">
                                    <textarea class="span9" name="ga" style="height: 169px; margin: 0px; width: 949px;"><?php echo $options['ga'] ?></textarea>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="input02">Meta keywords</label>
                                <div class="controls">
                                    <input id="tags_1" type="text" class="tags" name="keywords" value="<?php echo $options['keywords'] ?>"/>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Header</label>
                                <div class="controls">
                                    <textarea class="" name="header" id="header" style="height: 169px; margin: 0px; width: 949px;"><?php echo $options['header'] ?></textarea>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Footer</label>
                                <div class="controls">
                                    <textarea class="" name="footer" id="footer" style="height: 169px; margin: 0px; width: 949px;"><?php echo $options['footer'] ?></textarea>
                                </div>
                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-primary">Save changes</button>
                                <a class="btn" href="<?php echo $this->contextPath; ?>">Cancel</a>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>