<div class="widget did-you-know cycle cycle-diy">
    <h4 class="widget-title"><i class="fa fa-question-circle fa-lg"></i> Bạn có biết?</h4>
    <div class="slides" style="position: relative; width: 285px; height: 152px;">
        <div style="position: absolute; top: 0px; left: 0px; z-index: 4; opacity: 1; width: 285px; height: 61px; display: block;">
            <p>eDoctor- Chăm sóc sức khỏe toàn diện 24/7 là dịch vụ tổng đài tư vấn y tế trên toàn quốc (Telehealthcare) kết nối các bác sỹ, giáo sư hàng đầu trên khắp lãnh thổ Việt Nam để tư vấn các vấn đề về y tế, dinh dưỡng, sức khỏe và cấp cứu 24/24. <br>
            </p></div>

        <div style="position: absolute; top: 0px; left: 0px; display: none; z-index: 3; opacity: 0; width: 285px; height: 44px;">
            <p>Dù bạn ở bất kỳ đâu, tại bất cứ thời điểm nào 24/24, bạn đều có thể tiếp cận dễ dàng với các bác sỹ, chuyên gia hàng đầu của eDoctor để được tư vấn về các vấn đề sức khỏe của bạn và gia đình bạn. </p>
        </div>

        <div style="position: absolute; top: 0px; left: 0px; display: none; z-index: 3; opacity: 0; width: 285px; height: 152px;">
            <p>Dựa trên nền tảng công nghệ telehealthcare hiện đại, eDoctor hân hạnh mang tới các cá nhân và gia đình người Việt và các Doanh nghiệp, Tổ chức 1 giải pháp chăm sóc sức khỏe nhanh chóng, tiện lợi và tiết kiệm chi phí nhất.</p>

        </div>
    </div>
    <span class="widget-pager"></span>
</div>