<?php
$list = $this->list;
?>
<div class="row">
    <div class="span12">
        <div class="widget-block">
            <div class="widget-head">
                <h5><i class="black-icons list_images"></i> List</h5>
            </div>
            <div class="widget-content">
                <div class="widget-selectbox">
                    <ul>
                        <a class="btn btn-primary" href="<?php echo $this->contextPath ?>/add"><i class="icon-plus icon-white"></i> Add New</a>
                        <li class="right">
                            <div class="input-prepend"> <span class="add-on"><i class="icon-list-alt"></i></span>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="widget-box">
                    <table class="table task-tbl post-tbl table-striped">
                        <thead>
                            <tr>
                                <th width="5%" class="center"> # </th>
                                <th>Tiêu đề </th>
                                <th width="20%">Name seo </th>
                                <th width="20%">Danh mục </th>
                                <th width="10%" class="align-center">Trạng thái </th>
                                <th width="20%" class="align-center">Action </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($list):
                                $i = 1;
                                foreach ($list AS $item) :
                                    ?>
                                    <tr>
                                        <td class="center"><?php echo $i ?></td>
                                        <td><?php echo $item->art_name ?></td>
                                        <td><?php echo $item->art_seo ?></td>
                                        <td><?php  echo $item->cat_name;?></td>
                                        <td class="align-center">
                                            <?php
                                            if ($item->status == 1):
                                                ?>
                                                <a href="<?php echo $this->contextPath ?>/change?id=<?php echo $item->art_id ?>&page=<?php echo $this->currentPage ?>">
                                                    <img src="/layouts/admin/icons/yes.gif"/>
                                                </a>
                                                <?php
                                            else :
                                                ?>
                                                <a href="<?php echo $this->contextPath ?>/change?id=<?php echo $item->art_id ?>&page=<?php echo $this->currentPage ?>">
                                                    <img src="/layouts/admin/icons/no.gif"/>
                                                </a>
                                            <?php
                                            endif;
                                            ?>
                                        </td>
                                        <td class="align-center">
                                            <a href="<?php echo $this->contextPath ?>/edit?id=<?php echo $item->art_id; ?>" class="btn btn-success"><i class="icon-edit icon-white"></i> Edit</a>
                                            <a rel="<?php echo $this->contextPath ?>/delete?id=<?php echo $item->art_id; ?>" class="btnDeleteRow btn btn-danger"><i class="icon-trash icon-white"></i> Delete</a>
                                        </td>
                                    </tr>
                                    <?php
                                    $i++;
                                endforeach;
                                ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>

                <div class="widget-bottom">
                    <?php echo $this->page; ?>
                </div>

            </div>
        </div>
    </div>
</div>
<div class="widget-bottom">
    <div><?php echo $this->page_title ?></div>
</div>