<?php
$listCat = $this->listCat;
?>
<div class="row">
    <div class="span12">
        <div class="widget-block">
            <div class="widget-head">
                <h5> Form ELements</h5>
            </div>
            <div class="widget-content">
                <div class="widget-box">
                    <form class="form-horizontal well white-box" method="post" action="" enctype="multipart/form-data">
                        <?php if(isset($this->error)){
                            echo '<p class="alert alert-danger"><strong>'.$this->error.'</strong></p>';
                        } elseif(isset($_GET['update'])) {
                            echo '<p class="alert alert-success"><strong>Cập nhật bài viết thành công!</strong></p>';
                        }  ?>
                        <fieldset>
                            <div class="control-group">
                                <label class="control-label">Tiêu đề</label>
                                <div class="controls">
                                    <input type="text" class="span4" name="title" value="<?php if (!empty($this->editPost['title'])) echo $this->editPost['title'] ?>"/>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Link ảnh</label>
                                <div class="controls">
                                    <input type="text" class="span4" name="thumb" value="<?php if (!empty($this->editPost['thumb'])) echo $this->editPost['thumb'] ?>"/>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Danh mục</label>
                                <div class="controls">
                                    <select name='cat' class="span4">
                                        <?php foreach ($listCat AS $cat): ?>
                                            <option value="<?php echo $cat['_id']; ?>" <?php if ($cat['_id'] == $this->editPost['cat']) echo "selected='selected'" ?>><?php echo $cat['name']; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Mô tả ngắn</label>
                                <div class="controls">
                                    <textarea class="span10" placeholder="Mô tả ngắn" name="excerpt"><?php echo $this->editPost['excerpt'] ?></textarea>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Nội dung</label>
                                <div class="controls">
                                    <textarea class="span8" placeholder="Mô tả ngắn" name="content" id="content" class="ckeditor"><?php echo $this->editPost['content'] ?></textarea>
                                </div>
                            </div>
                            <?php if(isset($this->current_tag)) $tags = implode(',', $this->current_tag) ?>
                            <div class="control-group">
                                <label class="control-label" for="input02">Tags</label>
                                <div class="controls">
                                    <input id="tags_1" type="text" class="tags" name="tags" value="<?php if(isset($tags)) echo $tags; ?>"/>
                                </div>
                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-primary">Cập nhật bài viết</button>
                                <a class="btn" href="<?php echo $this->contextPath; ?>">Huỷ bỏ</a>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        var forder = '/upload/house';
        $('#image').uploadify({
            'formData': {
                'folder': forder,
                'fileext': 'png|gif|jpg|jpeg|bmp|JPG|PNG|GIF|JPEG|BMP',
                'thumb': '1'
            },
            'fileSizeLimit': 10000,
            'fileTypeExts': '*.png; *.gif; *.jpg; *jpeg; *.bmp;*.JPG;*.GIF;*.JPEG,*.PNG,*.BMP',
            'swf': '/layouts/admin/js/uploadify/uploadify.swf',
            'uploader': '/admin/upload/no-thumb',
            'cancelImg': '/layouts/admin/js/uploadify/uploadify-cancel.png',
            'multi': false,
            'onUploadSuccess': function(file, data) {
                var response_code = data.substring(0, 1);
                var file_name = data.substring(2);
                var data = forder + '/' + file_name;
                if (response_code == 0) {
                    $("#popup-content").html(file_name);
                    $("#show-popup").click();
                } else {
                    show_image(data);
                }
            }
        });
    });
    function show_image(data) {
        var img = "<input name = 'image' value = '" + data + "' type='hidden'>" + '<img src="' + data + '"/>';
        $("#show_image").html(img);
    }


    CKEDITOR.replace('content',
            {
                toolbar:
                        [
                            {name: 'document', items: ['Source']},
                            {name: 'basicstyles', items: ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript']},
                            {name: 'paragraph', items: ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl']},
                            {name: 'links', items: ['Link', 'Unlink', 'Anchor']},
                            {name: 'insert', items: ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak']},
                            {name: 'styles', items: ['Styles', 'Format', 'Font', 'FontSize']},
                            {name: 'colors', items: ['TextColor', 'BGColor']},
                        ],
                height: 300,
            });
</script>