<?php
$list = $this->postsList;
$totalRecords = $this->totalRecords;
$recordPerPage = $this->recordPerPage;
$pageNum = $totalRecords/$recordPerPage;
?>
<div class="row">
    <div class="span12">
        <div class="widget-block">
            <div class="widget-head">
                <h5><i class="black-icons list_images"></i> List</h5>
            </div>
            <form action="<?php echo $this->contextPath ?>?" method="get" accept-charset="utf-8">
              <input type="text" name="link" value="http://vnexpress.net/rss/so-hoa.rss" placeholder="">
              <input type="submit" name="" value="Okay">
            </form>
            <div class="widget-content">
                <div class="widget-selectbox">
                    <ul>
                        <a class="btn btn-primary" href="<?php echo $this->contextPath ?>/add"><i class="icon-plus icon-white"></i> Add New</a>
                        <li class="right">
                            <div class="input-prepend"> <span class="add-on"><i class="icon-list-alt"></i></span>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="widget-box">
                    <table class="table task-tbl post-tbl table-striped">
                        <thead>
                            <tr>
                                <th width="5%" class="center">#</th>
                                <th width="">Name</th>
                                <th width="">Nổi bật</th>
                                <th width="10%" class="align-center">Status</th>
                                <th width="20%" class="align-center">Danh mục</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($list):
                                $i = 1;
                                foreach ($list AS $post) :
                                    ?>
                                    <tr>
                                        <td class="center"><?php echo $i ?></td>
                                        <td><?php echo $post['title']; ?></td>
                                        <td class="align-center">
                                           
                                        </td>
                                        <td class="align-center">
                                        </td>
                                        <td class="align-center">
                                            <a href="<?php echo $this->contextPath ?>/edit?id=<?php echo $post['_id']; ?>" class="btn btn-success"><i class="icon-edit icon-white"></i> Edit</a>
                                            <a rel="<?php echo $this->contextPath ?>/delete?id=<?php echo $post['_id']; ?>" class="btnDeleteRow btn btn-danger"><i class="icon-trash icon-white"></i> Delete</a>
                                        </td>
                                    </tr>
                                    <?php
                                    $i++;
                                endforeach;
                                ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>

                <div class="widget-bottom">
                    
                </div>

            </div>
        </div>
    </div>
</div>
<div class="widget-bottom">
    <div><?php echo $this->page_title ?></div>
</div>