<?php
$errors = $this->errors;
$step = $this->step;
?>
<!-- ARTICLE -->
<div id="article" class="curvyRedraw">
    <div id="padding2">
        <fieldset>
            <legend class="mgb20">Xác thực tài khoản</legend>
            <?php if ($errors): ?>
                <div class="alert alert-error" style="width: 80%; margin: 0 auto 10px;">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <?php echo $errors; ?>
                </div>
            <?php endif; ?>
            <?php if ($this->m): ?>
                <div class="alert alert-error" style="width: 90%; margin: 0 auto 10px;">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <?php echo $this->m; ?>
                </div>
            <?php endif; ?>
            <?php if ($this->success): ?>
                <div class="alert alert-success" style="width: 90%; margin: 0 auto 10px;">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <?php echo $this->success; ?>
                </div>
            <?php endif; ?>
            <?php if ($step != 3): ?>
                <form class="form-horizontal" action="" method="POST">
                    <?php if ($step == 2): ?>
                        <input type="hidden" name="step" value="<?php echo $step ?>"/>
                        <input type="hidden" name="mobile" value="<?php echo $this->mobile ?>"/>
                        <div class="control-group">
                            <label class="control-label" for="inputEmail">Mã kích hoạt</label>
                            <div class="controls">
                                <input type="text" id="activecode" placeholder="Mã kích hoạt" name="activecode" value="<?php if ($this->mobile) echo $this->activecode ?>">
                            </div>
                        </div>
                    <?php else: ?>
                        <input type="hidden" name="step" value="1"/>
                        <div class="control-group">
                            <label class="control-label" for="inputEmail">Số điện thoại</label>
                            <div class="controls">
                                <input type="text" id="mobile" placeholder="Số điện thoại" name="mobile" value="<?php if ($this->mobile) echo $this->mobile ?>">
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="control-group">
                        <label class="control-label" for="captchar"></label>
                        <div class="controls">
                            <img src="/member/captcha?sid=<?php echo md5(uniqid(time())); ?>" id="captcha_image" height="55"/>
                            <a href="javascript:void(0);" onclick="document.getElementById('captcha_image').src = '/member/captcha?sid=' + Math.random();
                                    return false">
                                <img border="0" src="/layouts/default/img/refresh.gif" alt="Đổi ảnh khác" title="Đổi ảnh khác"/>
                            </a>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="captchar">Nhập mã kiểm tra</label>
                        <div class="controls">
                            <input type="text" id="captcha" placeholder="Mã kiểm tra" name="captcha" value="<?php if ($this->captcha) echo $this->captcha ?>">
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="controls">
                            <button type="submit" class="btn btn-info">Tiếp tục</button>
                        </div>
                    </div>
                </form>
            <?php endif; /* endif step !=3 */ ?>
        </fieldset>
    </div>
</div>
<!-- END ARTICLE -->
<!-- SIDEBAR --> 
<div id="sidebar">
    <div class="widget did-you-know cycle cycle-diy">
        <?php echo $this->render('profile.phtml'); ?>
    </div>
    <div class="widget did-you-know cycle cycle-diy">
        <?php echo $this->render('right.phtml'); ?>
    </div>
</div>
<!-- END SIDEBAR --> 