<?php $data = $this->data; ?>
<!-- ARTICLE -->
<div id="article" class="curvyRedraw">
    <div id="padding2">
        <fieldset>
            <legend class="mgb10">lịch sử cuộc gọi</legend>
            <table class="table table-striped" style="background-color: #fff;">
                <thead>
                    <tr>
                        <th style="text-align: left;">Thời điểm gọi</th>
                        <th style="text-align: left;">Nghe tư vấn</th>
                        <th style="text-align: left;">Tổng thời gian</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data AS $item): ?>
                        <tr>
                            <td><?php echo date('d/m/Y H:i:s', $item->dialTime / 1000) ?></td>
                            <td>
                                <?php if ($item->fileName) {
                                    ?>
                                    <audio controls="">
                                        <source src="http://cdn.edoctor.vn/callcenter/recording/<?php echo $item->fileName ?>" type="audio/wav">
                                    </audio> 
                                    <?php
                                } else {
                                    ?>

                                    <?php
                                }
                                ?>
                            </td>
                            <td style="text-align: right;"><?php echo $item->duration ?> s</td>
                        </tr>
                    <?php endforeach; ?>

                </tbody>
            </table>
    </div>
</div>
<!-- END ARTICLE -->
<!-- SIDEBAR --> 
<div id="sidebar">
    <div class="widget did-you-know cycle cycle-diy">
        <?php echo $this->render('profile.phtml'); ?>
    </div>
    <?php echo $this->render('right.phtml'); ?>
</div>
<!-- END SIDEBAR --> 