<?php $errors = $this->errors; ?>
<!-- ARTICLE -->
<div id="article" class="curvyRedraw">
    <fieldset>
        <legend style="color: #A80209; padding: 0 5px;">Thay đổi mật khẩu</legend>
        <form class="form-horizontal" action="" method="POST">
            <?php if ($errors): ?>
                <div class="alert alert-error" style="width: 80%; margin: 0 auto 10px;">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <?php echo $errors; ?>
                </div>
            <?php endif; ?>
            <?php if ($this->success): ?>
                <div class="alert alert-success" style="width: 80%; margin: 0 auto 10px;">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <?php echo $this->success; ?>
                </div>
            <?php endif; ?>
            <?php if ($this->m): ?>
                <div class="alert alert-error" style="width: 80%; margin: 0 auto 10px;">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <?php echo $this->m; ?>
                </div>
            <?php endif; ?>
            <div class="control-group">
                <label class="control-label" for="inputEmail">Mật khẩu cũ</label>
                <div class="controls">
                    <input type="password" id="password" placeholder="Mật khẩu cũ" name="old_pass">
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="inputEmail">Mật khẩu mới</label>
                <div class="controls">
                    <input type="password" id="password" placeholder="Mật khẩu mới" name="new_pass">
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="inputEmail">Nhập lại mật khẩu </label>
                <div class="controls">
                    <input type="password" id="password" placeholder="Nhập lại mật khẩu" name="renew_pass">
                </div>
            </div>

            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn btn-primary">Thay đổi</button>
                </div>
            </div>
        </form>
    </fieldset>
</div>
<!-- END ARTICLE -->
<!-- SIDEBAR --> 
<div id="sidebar">
    <div class="widget did-you-know cycle cycle-diy">
        <?php echo $this->render('profile.phtml'); ?>
    </div>
    <?php echo $this->render('right.phtml'); ?>
</div>
<!-- END SIDEBAR --> 