<?php $data = $this->data; ?>
<!-- ARTICLE -->
<div id="article" class="curvyRedraw">
    <div id="padding2">
        <fieldset>
            <legend class="mgb10">Lịch sử mua hàng</legend>
            <table class="table table-striped" style="background-color: #fff;">
                <thead>
                    <tr>
                        <td style="text-align: left;">Mã đơn hàng</td>
                        <td style="text-align: left;">Chi tiết</td>
                        <td style="text-align: left;">Thời gian</td>
                        <td style="text-align: left;">Trạng thái</td>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if ($data):
                        foreach ($data AS $item):
                            $exts = json_decode($item->exts);
                            ?>
                            <tr>
                                <td><?php echo $item->code ?></td>
                                <td>
                                    <p><b>Họ và tên: </b><?php echo $exts->full_name ?></p>
                                    <p><b>SĐT: </b><?php echo $exts->mobile ?></p>
                                    <p><b>Địa chỉ: </b><?php echo $exts->address ?>, <?php echo $exts->district_name ?>, <?php echo $exts->privince_name ?></p>
                                    <?php foreach ($item->goods AS $v): ?>
                                        <p><?php echo $v->goodName ?>/<?php echo number_format($v->goodPrice) ?>, số lượng <?php echo $v->quantity ?></p>
                                    <?php endforeach; ?>
                                </td>
                                <td><?php echo date('d/m/Y H:i:s', $item->orderDate / 1000) ?></td>
                                <td><?php echo $item->statusCode ?></td>
                            </tr>
                            <?php
                        endforeach;
                    endif;
                    ?>
                </tbody>
            </table>
        </fieldset>
    </div>
</div>
<!-- END ARTICLE -->
<!-- SIDEBAR --> 
<div id="sidebar">
    <div class="widget did-you-know cycle cycle-diy">
        <?php echo $this->render('profile.phtml'); ?>
    </div>
    <?php echo $this->render('right.phtml'); ?>
</div>
<!-- END SIDEBAR --> 