<?php
$errors = $this->errors;
$user = $this->user;
?>
<!-- ARTICLE -->
<div id="article" class="curvyRedraw">
    <div id="padding2">
        <fieldset>
            <legend>Cập nhật tài khoản</legend>
<?php if ($this->notice): ?>
                <div class="alert alert-error" style="width: 90%; margin: 0 auto 20px;">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                <?php echo $this->notice; ?>
                </div>
            <?php endif; ?>
<?php if ($this->success): ?>
                <div class="c-success">
                    <h1 style="font-size: 18px">Bạn đã đăng ký thành công tài khoản tại eDoctor.vn!</h1>
                    <p class="b-success__number">
                        <span class="b-success__order-text">Bạn có thể đăng nhập với email</span>
                        <span class="b-success__order-number"><b><?php echo $this->email; ?></b></span>
                    </p>
                    <p class="b-success__number">
                        <span class="b-success__order-text"> Vui lòng click <b><a href="/onepage.htm" class="help">vào đây</a></b> để tiếp tục mua thẻ tại eDoctor.vn.</span>
                    </p>
                </div>
<?php else: ?>
                <form class="form-horizontal" action="" method="POST">
                    <div class="control-group">
                        <div style="text-align: center; font-style: italic; font-weight: bold;">
                            Bạn vui lòng nhập mật khẩu để có thể đăng nhập bằng email.
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="inputEmail">Email</label>
                        <div class="controls">
                            <input type="text" name="email" class="span4" readonly="readonly" value="<?php echo $user['email'] ?>">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="inputPassword">Mật khẩu</label>
                        <div class="controls">
                            <input type="password" placeholder="Mật khẩu" name="password" class="span4">
                            <?php if ($errors['password_error']): ?>
                                <span class="help-block has-error"><?php echo $errors['password_error'] ?></span>
    <?php endif; ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="inputPassword">Nhập lại mật khẩu</label>
                        <div class="controls">
                            <input type="password" placeholder="Nhập lại mật khẩu" name="repassword" class="span4">
                            <?php if ($errors['repassword_error']): ?>
                                <span class="help-block has-error"><?php echo $errors['repassword_error'] ?></span>
    <?php endif; ?>
                        </div>
                    </div>
                    <div class="control-group" style="margin-top: 20px;">
                        <div class="controls">
                            <button type="submit" class="btn btn-primary">Cập nhật</button>
                        </div>
                    </div>
                </form>
<?php endif; ?>
        </fieldset>
    </div>
</div>
<!-- END ARTICLE -->
<!-- SIDEBAR --> 
<div id="sidebar">
    <div class="widget did-you-know cycle cycle-diy">
<?php echo $this->render('right.phtml'); ?>
    </div>
</div>
<!-- END SIDEBAR --> 