<!-- <div class="dashboard-widget"> -->
<!--   <div class="row"> -->
<!--     <div class="span2"> -->
<!--       <div class="dashboard-wid-wrap"> -->
<!--         <div class="dashboard-wid-content"> <a href="#"> <i class="dashboard-icons-colors graphic_design_sl"></i> <span class="dasboard-icon-title">Dashboard</span> </a> </div> -->
<!--       </div> -->
<!--     </div> -->
<!--     <div class="span2"> -->
<!--       <div class="dashboard-wid-wrap"> -->
<!--         <div class="dashboard-wid-content"> <a href="#"> <i class="dashboard-icons-colors settings_sl"></i> <span class="dasboard-icon-title">Settings</span> </a> </div> -->
<!--       </div> -->
<!--     </div> -->
<!--     <div class="span2"> -->
<!--       <div class="dashboard-wid-wrap"> -->
<!--         <div class="dashboard-wid-content"> <a href="#"> <i class="dashboard-icons-colors customers_sl"></i> <span class="dasboard-icon-title">Users Lits</span> </a> </div> -->
<!--       </div> -->
<!--     </div> -->
<!--     <div class="span2"> -->
<!--       <div class="dashboard-wid-wrap"> -->
<!--         <div class="dashboard-wid-content"> <a href="#"> <i class="dashboard-icons-colors current_work_sl"></i> <span class="dasboard-icon-title">Statistics</span> </a> </div> -->
<!--       </div> -->
<!--     </div> -->
<!--     <div class="span2"> -->
<!--       <div class="dashboard-wid-wrap"> -->
<!--         <div class="dashboard-wid-content"> <a href="#"> <i class="dashboard-icons-colors archives_sl"></i> <span class="dasboard-icon-title">Content</span> </a> </div> -->
<!--       </div> -->
<!--     </div> -->
<!--     <div class="span2"> -->
<!--       <div class="dashboard-wid-wrap"> -->
<!--         <div class="dashboard-wid-content"> <a href="#"> <i class="dashboard-icons-colors lightbulb_sl"></i> <span class="dasboard-icon-title">Suport</span> </a> </div> -->
<!--       </div> -->
<!--     </div> -->
<!--   </div> -->
<!-- </div> -->

<!-- <div class="row"> -->
<!--   <div class="switch-board-round"> -->
<!--     <ul class="clearfix"> -->
<!--       <li><a href="#" class="tip-top" title="Add User"><span class="srabon-sprite plus_sl"></span></a></li> -->
<!--       <li><a href="#" class="tip-top" title="Add Post"><span class="srabon-sprite cv_sl"></span></a></li> -->
<!--       <li><a href="#" class="tip-top" title="Recent Order"><span class="srabon-sprite bank_sl"></span></a></li> -->
<!--       <li><a href="#" class="tip-top" title="Address Book"><span class="srabon-sprite address_sl"></span></a></li> -->
<!--       <li><a href="#" class="tip-top" title="Advance Search"><span class="srabon-sprite search_sl"></span></a></li> -->
<!--       <li><a href="#" class="tip-top" title="Events"><span class="srabon-sprite full_time_sl"></span></a></li> -->
<!--       <li><a href="#" class="tip-top" title="Upload Files"><span class="srabon-sprite upcoming_work_sl"></span></a></li> -->
<!--       <li><a href="#" class="tip-top" title="File Explorer "><span class="srabon-sprite category_sl"></span></a></li> -->
<!--       <li><a href="#" class="tip-top" title="Print"><span class="srabon-sprite print_sl"></span></a></li> -->
<!--     </ul> -->
<!--   </div> -->
<!-- </div> -->