<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php
    $configSite = $this->configSite;
    $titlePage = $this->titlePage;
    $keywords = $this->keywords;
    $description = $this->description;
    $parent = $this->parent;
    $module = $this->module;
    $controller = $this->controller;
    $action = $this->action;
    $user = $this->user;
    ?>
    <title><?php echo empty($titlePage) ? $configSite['title'] : $titlePage; ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="description" content="<?php echo empty($description) ? $configSite['description'] : $description; ?>"/>
    <meta name="keywords" content="<?php echo empty($keywords) ? $configSite['keywords'] : $keywords; ?>"/>
    <meta name="Author" content="" />
    <meta name="Robots" content="index,follow,noodp" />
    <?php if ($action == 'index') : ?>
    <!-- SEO by khuongnt -->
    <link rel="canonical" href="" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="" />
    <meta property="og:description" content="<?php echo empty($description) ? $configSite['description'] : $description; ?>" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta name="twitter:card" content="summary" />
    <!-- /SEO by khuongnt-->
    <?php endif; ?>
    <link rel="stylesheet" href="/layouts/default/css/jquery.bxslider.css" type="text/css" />
    <link href="/layouts/default/style.css" rel="stylesheet" type="text/css" />
    <script src="/layouts/default/js/jquery.js" type="text/javascript"></script>
    <script src="/layouts/default/js/jquery.bxslider.js" type="text/javascript"></script>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700&subset=latin,vietnamese' rel='stylesheet' type='text/css'>
    <?php echo $configSite['ga'] ?>
    </head>
    <body class="<?php if ($action == 'index' && $controller == 'index') {echo  'home';} else {echo 'single';} ?>">
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/vi_VN/all.js#xfbml=1";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
        <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
        <div class="full" id="header">
          <div class="rwidth">
            <a class="logo" href="/" title="">
              <img src="/layouts/default/images/tuansukien.png" alt="">
            </a>
            <div class="right-head">
              <strong></strong>
              <a href="#" title="">Tin 24h</a>
              <a class="bg-red" href="#" title="">Cần biết</a>
              <div><div class="g-plusone" data-size="medium"></div></div>
            </div>
          </div>
          <div class="nav full">
            <div class="rwidth">
              <ul>
                <li><a href="/tin-tuc/thoi-su">Thời sự</a></li>
                <li><a href="/tin-tuc/the-gioi">Thế giới</a></li>
                <li><a href="/tin-tuc/kinh-doanh">Kinh doanh</a></li>
                <li><a href="/tin-tuc/phap-luat">Pháp luật</a></li>
                <li><a href="/tin-tuc/the-thao">Thể thao</a></li>
                <li><a href="/tin-tuc/cong-nghe">Công nghệ</a></li>
                <li><a href="/tin-tuc/khoa-hoc">Khoa học</a></li>
                <li><a href="/tin-tuc/giao-duc">Giáo dục</a></li>
                <li><a href="/tin-tuc/giai-tri">Giải trí</a></li>
                <li><a href="/tin-tuc/oto-xe-may">Xe</a></li>
                <li><a href="/tin-tuc/doi-song">Đời sống</a></li>
                <li><a href="/tin-tuc/tinh-cam">Tình cảm</a></li>
                <li><a href="/tin-tuc/du-lich">Du lịch</a></li>
            </ul>
              <div id="search_form">
                <form action="/" method="get" accept-charset="utf-8">
                  <input type="text" name="s" value="" placeholder="Nhập từ khoá">
                  <input type="submit" name="" value="Tìm kiếm" placeholder="">
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="full event-line">
          <div class="rwidth">
            <ul class="full">
              <li><span>Dòng sự kiện</span></li>
              <li><a href="/tu-khoa/iphone-6" title="">iPhone 6</a></li>
              <li><a href="/tu-khoa/ngoai-hang-anh" title="">Ngoại hạng Anh</a></li>
            </ul>
          </div>
        </div>
        <div id="main" class="full">
          <div class="rwidth">
            <?php if ($action == 'index') : ?>
            <?php echo $this->layout()->content ?>
            <?php else: ?>
            <?php $luongsingle = $this->luongsingle; ?>
            <?php if ($luongsingle): ?>
                <?php echo $this->layout()->content ?>
            <?php else: ?>
                <?php echo $this->layout()->content ?>
            <?php endif; ?>

            <?php //echo $this->layout()->content ?>
        <?php endif; ?>	
        <div class="full ktbl ktbl2">
          <h2><span>Tin tổng hợp</span></h2>
          <div class="rwidth">
            <div style="display:table; width:930px; margin:0 auto;">
              <div class="slide_ktbl2">
               
                <div class="slide">
                  <a class="slide6" href="" title="">
                    <span></span>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>
<!--end main-->
<div id="footer" class="full">
    <div id="nav-footer" class="full">
        <div class="rwidth">
            <ul>
                <li><a href="/dich-vu-tu-van-cham-soc-suc-khoe.htm">Thẻ eDoctor</a></li>
                <li><a href="/loi-ich-cua-khach-hang.htm">Lợi ích của khách hàng</a></li>
                <li><a href="/huong-dan-su-dung.htm">Hướng dân sử dụng thẻ eDoctor</a></li>
                <li><a href="/quyen-loi.htm">Hệ thống các đối tác</a></li>
                <li><a href="/cham-soc-suc-khoe-ba-bau.htm">Chăm sóc bà bầu</a></li>
            </ul>
        </div>
    </div>
    <div id="bottom" class="full">
        <div class="rwidth">
            <div class="col-md-2">
                <a href="/" title=""><img src="/layouts/default/images/tuansukien.png" alt=""></a>
                <div class="clear"></div>
                
            </div>
        </div>
    </div>
</div>
<!--end footer-->
<script type="text/javascript">
  jQuery(document).ready(function($) {
    $('.slide_ktbl2').bxSlider({
      slideWidth: 300,
      minSlides: 4,
      maxSlides: 4,
      moveSlides: 1,
      slideMargin: 10
    });
    $('.search_nav a').click(function(event) {
        if($(this).hasClass('active')) {
            $(this).removeClass('active');
        } else {
            $(this).addClass('active');
        }
        $('#search_form').slideToggle('fast');
        return false;
    });
});
</script>
</body>
</html>