<?php ?>
<!-- ARTICLE -->
<div id="article" class="curvyRedraw">
    <div class="padding ">
        <div class="c-success">
            <h1>Cảm ơn bạn đã mua hàng tại eDoctor.vn !</h1>
            <p class="b-success__number">
                <span class="b-success__order-text"><i class="fa fa-hand-o-right"></i> Mã số đơn hàng của bạn:</span>
                <span class="b-success__order-number"><b><?php echo $this->code; ?></b></span>
            </p>
            <p>
                <span class="b-success__order-number">
                    <i class="fa fa-hand-o-right"></i> Nội dung gửi tiền quý khách vui lòng ghi theo mẫu (nếu chuyển qua phòng giao dịch, internet banking):
                </span>
                <span class="b-success__order-number">
                    <strong>Tên khách đặt hàng - Số điện thoại đặt hàng - Mã số đơn hàng</strong>
                    <br>
                    <i>Ví dụ: Nguyễn Văn A – 0909152355 – 8F392</i>
                </span>
            </p>
            <p class="b-success__number">
                <span class="b-success__order-text"><i class="fa fa-hand-o-right"></i> Chúng tôi sẽ liên hệ với quý khách hàng trong 24h tới để xác nhận thông tin và thời gian chuyển thẻ eDoctor.</span>
            </p>
            <p class="b-success__number">
                <span class="b-success__order-text"><i class="fa fa-hand-o-right"></i> Thông tin chi tiết về đơn hàng đã được <strong>gửi đến địa chỉ mail </strong><span class="b-success__email"><?php echo $this->email ?></span>. Bạn vui lòng kiểm tra hộp thư, nếu không tìm thấy vui lòng tìm thêm trong hộp thư Spam hoặc Junk Folder.</span>
            </p>
        </div>
    </div>
</div>
<!-- END ARTICLE -->
<!-- SIDEBAR --> 
<div id="sidebar">
    <div class="widget did-you-know cycle cycle-diy">
        <?php echo $this->render('right.phtml'); ?>
    </div>
</div>
<!-- END SIDEBAR --> 
