<?php
$list = $this->list;
$success = $this->success;
?>
<h1 class="title-bg"><strong>Đặt mua thẻ eDoctor</strong></h1>
<br />
<div class="contact-form" id="contact-form">
    <p>Đặt hàng mua thẻ eDoctor thành công</p> <br />
    <p class="note">
        <i class="fa fa-thumbs-up"></i>
        <span style="color:green; font-weight:bold;" class="thumbs-up">Gửi thành công. Chúng tôi sẽ liên hệ với bạn trong 24h tới!</span>
    </p>
</div>