<?php 
$list = $this->list;
$errors = $this->errors;
 ?>
<!-- ARTICLE -->
<div id="cartOder" class="curvyRedraw">
	<div id="widget">
		<ul class="clearfix anchor">
			<li><a href="#step-1" class="selected" isdone="1" rel="1">
			<span class="stepNumber">1</span>
			<span class="stepDesc"> Step 1 <small>Đăng nhập</small></span></a></li>
			<li><a href="#step-2" class="disabled" isdone="1" rel="2">
			<span class="stepNumber">2</span>
			<span class="stepDesc"> Step 2 <small>Địa chỉ giao hàng</small></span></a></li>
			<li><a href="#step-3" class="disabled" isdone="0" rel="3">
			<span class="stepNumber">3</span>
			<span class="stepDesc"> Step 3 <small>Thanh toán và đặt mua</small></span></a></li>
		</ul>
		<fieldset>
			<legend style="color: #A80209; padding: 0 5px;">&nbsp;</legend>
			<form class="form-horizontal" action="" method="POST">
				<div class="control-group">
				    <label class="control-label" for="inputEmail">Nhập vào Email:</label>
				    <div class="controls">
				      <input type="text" id="email" placeholder="Email" name="email" value="<?php if($this->email) echo $this->email?>">
				      <?php if($errors['email_null']):?>
				      <span class="help-block">A block of help text that breaks onto a new line and may extend beyond one line.</span>
				      <?php endif;?>
				    </div>
				</div>
				<div class="control-group">
					<div class="controls">
						<div class="radio">
						    <input type="radio" name="options" id="options" value="1" checked="checked">
						   	Đặt hàng không cần đăng ký tài khoản
						</div>
<!-- 						<div class="radio"> -->
<!-- 						    <input type="radio" name="options" id="options" value="2"> -->
<!-- 						    Tôi đã có tài khoản -->
<!-- 						</div> -->
					</div>
				</div>
<!-- 				<div class="control-group"> -->
<!-- 				    <label class="control-label" for="inputPassword">Password</label> -->
<!-- 				    <div class="controls"> -->
<!-- 				      <input type="password" id="inputPassword" placeholder="Password" name="password"> -->
<!-- 				    </div> -->
<!-- 				</div> -->
				<div class="control-group">
				    <div class="controls">
				      <button type="submit" class="btn btn-primary" id="step1">Tiếp tục</button>
				    </div>
				</div>
			</form>
		</fieldset>
	</div>
</div>
<!-- END ARTICLE -->
<!-- SIDEBAR --> 
<div id="sidebar">
    <div class="widget did-you-know cycle cycle-diy">
    	<h4 class="widget-title-cart">Thông tin đơn hàng</h4>
		<div class="order_cart" style="min-height: 152px;">
			<div>
			
			</div>
            	<table style="width: 285px">
                    <tbody>
                    	<tr>
                        	<td style="width: 50%;">Sản phẩm</td>
                            <td style="width: 20%">SL</td>
                            <td style="width: 30%">Giá</td>
                    	</tr>
                    	<?php 
                    		foreach ($list AS $item):
                    		$total+=$_SESSION['cart'][$item->pro_id]*$item->pro_price;
                    	?>
                    	<tr>
                    		<td><a href="#" title=""><?php echo $item->pro_name?></a></td>
                    		<td><?php echo $_SESSION['cart'][$item->pro_id] ?></td>
                    		<td><?php echo number_format($_SESSION['cart'][$item->pro_id]*$item->pro_price) ?></td>
                    	</tr>
                    	<?php endforeach;?>
                    	<tr>
                    		<td><span>Tổng cộng</span></td>
                    		<td></td>
                    		<td><?php echo number_format($total)?></td>
                    	</tr>
                    </tbody>
              </table>
		</div>
		<span class="widget-pager">
	</div>
</div>
<!-- END SIDEBAR --> 
<link rel="stylesheet" media="all" href="/layouts/default/css/vi_style_v3.css" type="text/css">