<style type="text/css" media="screen">
	.content-partner {min-height: 94px;}
</style>
<div id="banner-quyenloi">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1 class="element_from_left">Quyền lợi của khách hàng</h1>
						<p>Khi sử dụng dịch vụ tư vấn, <a style="color:#FFF;" href="http://edoctor.vn/dich-vu-tu-van-suc-khoe.htm"><strong style="font-weight:400;">chăm sóc sức khỏe</strong></a> - thẻ eDoctor</p>
					</div>
				</div>
			</div>
		</div>
		<!-- Services -->
		<div id="quyen-loi">
			<div class="container">
				<div class="row list-benhvien">
					<div class="col-md-12">
						<h2 class="element_from_left">Các bệnh viện/ phòng khám</h2>
					</div>
					<div class="col-md-4 col3 element_fade_in">
						<a href="#" title=""><img src="/layouts/responsive/img/benh-vien-bao-son.jpg"></a>
						<h3>Phòng khám đa khoa Bảo Sơn</h3>
						<div class="col-md-12">
							<div class="row">
								<span class="add"><i class="fa fa-map-marker"></i> 52 Nguyễn Chí Thanh, Đống Đa, HN</span> 
								<span class="phone"><i class="fa fa-phone"></i> (04) 3 775 7099</span>
								<span class="sales">Chiết khấu: <strong>10%</strong></span>
							</div>
						</div>
						<div class="col-md-6">
							<div class="row">
								<strong>Dịch vụ</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> Khám sức khỏe định kì</li>
									<li><i class="fa fa-check"></i> Khám sức khỏe trọn gói</li>
									<li><i class="fa fa-check"></i> Dịch vụ bảo hiểm</li>
									<li><i class="fa fa-check"></i> Thẻ hội viên</li>
									<li><i class="fa fa-check"></i> Chăm sóc tại nhà</li>
								</ul>
							</div>
						</div>
						
						<div class="col-md-6">
							<div class="row">
								<strong>Chuyên môn</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> Sản phụ khoa & Hiếm muộn</li>
									<li><i class="fa fa-check"></i> Khoa Nhi</li>
									<li><i class="fa fa-check"></i> Ung bướu</li>
									<li><i class="fa fa-check"></i> Tim mạch</li>
									<li><i class="fa fa-check"></i> Xét ngiệm</li>
									<li><i class="fa fa-check"></i> Chuẩn đoán hình ảnh</li>
								</ul>
							</div>
						</div>
					</div>

					<div class="col-md-4 col3 element_fade_in">
						<a href="#" title=""><img src="/layouts/responsive/img/nha-khoa.jpg"></a>
						<h3>Nha khoa Đại Dương(Ocean Dental)</h3>
						<div class="col-md-12">
							<div class="row">
								<span class="add"><i class="fa fa-map-marker"></i> 200 Hoàng Quốc Việt, HN</span>
								<span class="phone"><i class="fa fa-phone"></i> 0979557789</span>
								<span class="sales">Chiết khấu: <strong>5% - 10%</strong></span>
							</div>
						</div>
						<div class="col-md-6">
							<div class="row">
								<strong>Dịch vụ</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> Dịch vụ về nha khoa</li>
								</ul>
							</div>
						</div>
						
						<div class="col-md-6">
							<div class="row">
								<strong>Chuyên môn</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> Nha khoa</li>
								</ul>
							</div>
						</div>
					</div>

					<div class="col-md-4 col3 element_fade_in">
						<a href="#" title=""><img src="/layouts/responsive/img/cham-soc-suc-khoe.jpg"></a>
						<h3>Phòng khám SPK Đoàn Thị Tuấn</h3>
						<div class="col-md-12">
							<div class="row">
								<span class="add"><i class="fa fa-map-marker"></i> Số 8 Dốc phụ sản</span>
								<span class="phone"><i class="fa fa-phone"></i> 0984441886</span> 
								<span class="sales">Chiết khấu: <strong>15%</strong></span>
							</div>
						</div>
						<div class="col-md-6">
							<div class="row">
								<strong>Dịch vụ</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> Khám sản</li>
									<li><i class="fa fa-check"></i> Khám phụ khoa</li>
									<li><i class="fa fa-check"></i> Khám thai nhi định kỳ</li>
									<li><i class="fa fa-check"></i> Chăm sóc sức khỏe bà bầu</li>
								</ul>
							</div>
						</div>
						
						<div class="col-md-6">
							<div class="row">
								<strong>Chuyên môn</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> Sản khoa</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="clear"></div>
					<div class="col-md-4 col3 element_fade_in">
						<a href="#" title=""><img src="/layouts/responsive/img/nha-khoa-hsl.jpg"></a>
						<h3>Nha khoa HSL</h3>
						<div class="col-md-12">
							<div class="row">
								<span class="add"><i class="fa fa-map-marker"></i> 25A1 Trần Duy Hưng</span> 
								<span class="phone"><i class="fa fa-phone"></i> 0982.0982.88 - 0915.313.898</span>
								<span class="sales">Chiết khấu: <strong>N/A</strong></span>
							</div>
						</div>
						<div class="col-md-6">
							<div class="row">
								<strong>Dịch vụ</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> Làm răng giả</li>
									<li><i class="fa fa-check"></i> Răng sứ thẩm mỹ</li>
									<li><i class="fa fa-check"></i> Hàn răng</li>
									<li><i class="fa fa-check"></i> Điều trị tủy răng</li>
									<li><i class="fa fa-check"></i> Làm trắng răng</li>
								</ul>
							</div>
						</div>
						
						<div class="col-md-6">
							<div class="row">
								<strong>Chuyên môn</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> Nha khoa</li>
									<li><i class="fa fa-check"></i> Răng hàm mặt</li>
									<li><i class="fa fa-check"></i> Thẩm mỹ răng</li>
								</ul>
							</div>
						</div>
					</div>

					<div class="col-md-4 col3 element_fade_in">
						<a href="#" title=""><img src="/upload/images/benh-vien-dong-do.jpg"></a>
						<h3>Bệnh viện Đông Đô</h3>
						<div class="col-md-12">
							<div class="row">
								<span class="add"><i class="fa fa-map-marker"></i> Số 5 Xã Đàn, Đống Đa, HN</span> 
								<span class="phone"><i class="fa fa-phone"></i> 04.62784449</span>
								<span class="sales">Chiết khấu: <strong>10%</strong></span>
							</div>
						</div>
						<div class="col-md-6">
							<div class="row">
								<strong>Dịch vụ</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> Kiểm tra sức khỏe định kì </li>
									<li><i class="fa fa-check"></i> Khám bệnh tim mạch </li>
									<li><i class="fa fa-check"></i> Phẫu thuật tim mạch</li>
									<li><i class="fa fa-check"></i> Phục hồi chức năng tim mạch</li>
									<li><i class="fa fa-check"></i> Cấp cứu ngoại viện</li>
									<li><i class="fa fa-check"></i> Điều trị nội, ngoại trú</li>
								</ul>
							</div>
						</div>
						
						<div class="col-md-6">
							<div class="row">
								<strong>Chuyên môn</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> Tim mạch</li>
									<li><i class="fa fa-check"></i> Cơ - xương - khớp</li>
									<li><i class="fa fa-check"></i> Răng hàm mặt</li>
									<li><i class="fa fa-check"></i> Tai mũi họng</li>
									<li><i class="fa fa-check"></i> Mắt</li>
								</ul>
							</div>
						</div>
					</div>

					<div class="col-md-4 col3 element_fade_in">

					</div>
				</div>
				<!---->
				<div class="row list-spa">
					<div class="col-md-12">
						<h2 class="element_from_left">Các trung tâm Fitness, Spa</h2>
					</div>
					<div class="col-md-4 col3 element_fade_in">
						<a href="#" title=""><img src="/layouts/responsive/img/muaxuan.jpg"></a>
						<h3>Câu lạc bộ thể dục Mùa xuân (Spring Club)</h3>
						<div class="col-md-12 content-partner">
							<div class="row">
								<span class="add"><i class="fa fa-map-marker"></i> 69 Trần Nhân Tông, Hai Bà Trưng, HN</span>
								<span class="phone"><i class="fa fa-phone"></i> (04) 3 942 6645</span>
								<span class="sales">Chiết khấu: <strong>10%</strong>(thẻ 01 và 03 tháng) - <strong>20%</strong>(thẻ 06 và 12 tháng)</span>
							</div>
						</div>
						<div class="clear"></div>
						<div class="col-md-12">
							<div class="row">
								<strong>Dịch vụ</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> GYM Fitness</li>
									<li><i class="fa fa-check"></i> Lớp yoga</li>
									<li><i class="fa fa-check"></i> Lớp aerobic</li>
									<li><i class="fa fa-check"></i> Bellydance</li>
									<li><i class="fa fa-check"></i> Tennis</li>
									<li><i class="fa fa-check"></i> Bể bơi và billard</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-md-4 col3 element_fade_in">
						<a href="#" title=""><img src="/layouts/responsive/img/spa-royal.png"></a>
						<h3>Royal Beauty Spa</h3>
						<div class="col-md-12 content-partner">
							<div class="row">
								<span class="add"><i class="fa fa-map-marker"></i> số 116 Thái Thịnh 2, Láng Hạ, Đống Đa, HN</span>
								<span class="phone"><i class="fa fa-phone"></i> 0462525858 - 0913399289</span>
								<span class="sales">Chiết khấu: <strong>20% - 25%</strong></span>
							</div>
						</div>
						<div class="clear"></div>
						<div class="col-md-12">
							<div class="row">
								<strong>Dịch vụ</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> Chăm sóc da</li>
									<li><i class="fa fa-check"></i> Massage Body</li>
									<li><i class="fa fa-check"></i> Tẩy chết da toàn thân</li>
									<li><i class="fa fa-check"></i> Giảm béo</li>
									<li><i class="fa fa-check"></i> Tắm trắng toàn thân</li>
									<li><i class="fa fa-check"></i> Đặc trị da sau sinh</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-md-4 col3 element_fade_in">
						<a href="#" title=""><img src="/upload/images/trung-tam-lam-dep-zennova.jpg"></a>
						<h3>Zennova Spa</h3>
						<div class="col-md-12 content-partner">
							<div class="row">
								<span class="add"><i class="fa fa-map-marker"></i> CS1: 113 ngõ Núi Trúc, Núi Trúc, Ba Đình, HN</span> <br>
								<span class="add"><i class="fa fa-map-marker"></i> CS2: 988 Nguyễn Khoái,Quận Hoàng Mai, HN</span>
								<span class="phone"><i class="fa fa-phone"></i> 04.37.365.566 - 04.22.468.988</span>
								<span class="sales">Chiết khấu: <strong>N/A</strong></span>
							</div>
						</div>
						<div class="clear"></div>
						<div class="col-md-12">
							<div class="row">
								<strong>Dịch vụ</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> Spa giường nóng eco</li>
									<li><i class="fa fa-check"></i> Massage thảo dược</li>
									<li><i class="fa fa-check"></i> Thiền và yoga</li>
									<li><i class="fa fa-check"></i> Tư vấn dinh dưỡng</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="clear"></div>
					<div class="col-md-4 col3 element_fade_in">
						<a href="#" title=""><img src="/upload/images/tp-spa.jpg"></a>
						<h3>TP Spa</h3>
						<div class="col-md-12 content-partner">
							<div class="row">
								<span class="add"><i class="fa fa-map-marker"></i> 98 An Trạch, Cát Linh, Đống Đa, HN</span>
								<span class="phone"><i class="fa fa-phone"></i> 0422163396</span>
								<span class="sales">Chiết khấu: <strong>30%</strong></span>
							</div>
						</div>
						<div class="clear"></div>
						<div class="col-md-12">
							<div class="row">
								<strong>Dịch vụ</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> Massage body</li>
									<li><i class="fa fa-check"></i> Làm trắng toàn thân</li>
									<li><i class="fa fa-check"></i> Công nghệ giảm béo toàn thân</li>
									<li><i class="fa fa-check"></i> Chăm sóc da</li>
									<li><i class="fa fa-check"></i> Xóa Xăm bằng công nghệ Lazer</li>
									<li><i class="fa fa-check"></i> Làm đẹp không cần phẫu thuật</li>
									<li><i class="fa fa-check"></i> Tẩy nốt ruồi + uốn mi</li>
								</ul>
							</div>
						</div>
					</div>

				</div>

				<div class="row list-tainha">
					<div class="col-md-12">
						<h2 class="element_from_left">Dịch vụ tại nhà</h2>
					</div>
					<div class="col-md-4 col3 element_fade_in">
						<a href="#" title=""><img src="/layouts/responsive/img/tam-be-tai-nha.png"></a>
						<h3>Tắm bé và chăm sóc sau sinh tại nhà Hồng Liên</h3>
						<div class="col-md-12">
							<div class="row">
								<span class="add"><i class="fa fa-map-marker"></i> 1K16 Tương Mai, Hoàng Mai, Hà Nội</span> 
								<span class="phone"><i class="fa fa-phone"></i> 0984806698 - 0946862685</span>
								<span class="sales">Chiết khấu: <strong>10%</strong></span>
							</div>
						</div>
						<div class="col-md-6">
							<div class="row">
								<strong>Dịch vụ</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> Tắm trẻ sơ sinh</li>
									<li><i class="fa fa-check"></i> Chăm sóc mẹ sau sinh</li>
									<li><i class="fa fa-check"></i> Dịch vụ y tế tại nhà</li>
								</ul>
							</div>
						</div>
						<div class="col-md-6">
							<div class="row">
								<strong>Chuyên môn</strong>
								<ul class="list-services">
									<li><i class="fa fa-check"></i> Nhi/ Sản khoa</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Services end -->

		<!-- Purchase -->
		<div class="purchase">
			<div class="container">
				<div class="row">
					<div class="col-md-9">
						<p><i class="fa fa-hand-o-right"></i> Mua thẻ <a style="color:#FFF;" href="http://edoctor.vn/the-cham-soc-suc-khoe-edoctor.htm">chăm sóc sức khỏe</a> eDoctor ngay hôm này để được hưởng các chương trình ưu đãi<br />
						<span>Chỉ cần gọi về Tổng đài 18006115 (miễn phí cước gọi) - hàng trăm bác sĩ là các Giáo sư, tiến sĩ… đang chờ điện thoại của bạn.</span></p>
					</div>
					<div class="col-md-3 purchase-button element_from_right">
						<a href="http://edoctor.vn/the-cham-soc-suc-khoe-edoctor.htm" title="Thẻ chăm sóc sức khỏe eDoctor" class="btn btn-default btn-green">Mua online</a>
					</div>
				</div>
			</div>
		</div>
		<!-- Purchase end -->