<?php
$list = $this->list;
$total = 0;
?>
<link rel="stylesheet" media="all" href="/layouts/default/css/vi_style_v3.css" type="text/css">
<link rel="stylesheet" media="all" href="/layouts/default/css/font-awesome.min.css" type="text/css">
<style type="text/css" media="screen">
    .cart_buy_logo {background: none !important; padding-left: 0 !important;}
    .cart-info thead {background-color: #f3f3f3; border: 1px solid #e8e8e8; border-bottom: none;}
    #tbody-cart .name span {
        font-size: 15px; margin-top: 20px !important;
        float: left; color: #00315e;
    }
    .btn-flat {display: block; height: 35px;background: #0088cc; font-size: 13px; text-align: center;
               color: #FFF !important; text-transform: uppercase; border-radius: 3px;display: block; line-height: 35px;
               -webkit-transition:0.3s all ease-in-out;
               -moz-transition:0.3s all ease-in-out;
               -ms-transition:0.3s all ease-in-out;
               transition:0.3s all ease-in-out;
    }
    .btn-flat:hover {
        color: #FFF; background-color: #a70d17;
    }
    .btn-cam {
        background: #f3d078;
        background: -moz-linear-gradient(top,#f7dfa5,#f0c14b);
        background: -webkit-gradient(linear,left top,left bottom,color-stop(0%,#f7dfa5),color-stop(100%,#f0c14b));
        background: -webkit-linear-gradient(top,#f7dfa5,#f0c14b);
        background: -o-linear-gradient(top,#f7dfa5,#f0c14b);
        background: -ms-linear-gradient(top,#f7dfa5,#f0c14b);
        background: linear-gradient(top,#f7dfa5,#f0c14b);
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#f7dfa5',endColorstr='#f0c14b',GradientType=0);
        border-radius:3px;
        -webkit-border-radius:3px;
        -moz-border-radius:3px;
        vertical-align: middle;
        border: 1px solid;
        border-color: #cba957 #bf942a #aa8326;
        color: #111;
        padding: 10px 20px !important;
        -webkit-box-shadow:0 1px 0 rgba(255,255,255,0.4) inset;-moz-box-shadow:0 1px 0 rgba(255,255,255,0.4) inset;box-shadow:0 1px 0 rgba(255,255,255,0.4) inset;
    }
    .btn-cam:hover {
        text-decoration: none; color: #111;
        border-color: #c59f43 #aa8326 #957321;
        background:#f1c860;background:-moz-linear-gradient(top,#f5d78e,#eeb933);
        background:-webkit-gradient(linear,left top,left bottom,color-stop(0%,#f5d78e),color-stop(100%,#eeb933));
        background:-webkit-linear-gradient(top,#f5d78e,#eeb933);background:-o-linear-gradient(top,#f5d78e,#eeb933);
        background:-ms-linear-gradient(top,#f5d78e,#eeb933);
        background:linear-gradient(top,#f5d78e,#eeb933);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#f5d78e',endColorstr='#eeb933',GradientType=0);*zoom:1
    }
    input:focus, input:active {outline: none;}
    .sub_total .checkout a {float: right; padding: 0 18px;}
    .cart-info tbody .total {color: #b12704!important;}
    .cart_buy_logo {color: #090!important;}
</style>
<script src="/layouts/default/js/jquery.js"></script>
<script src="/layouts/default/js/common.js"></script>
<div id="shopping-cart-content" class="shopping-cart-content" style="width: 650px;">
    <form action="" method="POST">
        <div id="shopping-cart-header">
            <div id="msg_shoppingcart">
                <div class="cart_buy_logo"><i class="fa fa-check"></i> Thẻ eDoctor đã được thêm vào giỏ hàng</div>
            </div>
            <div style="clear: both"></div>
        </div>
        <div class="cart-info">
            <table>
                <thead>
                    <tr>
                        <td class="title_image"></td>
                        <td class="title_name"></td>
                        <td class="title_price">Đơn giá</td>
                        <td class="title_quantity">Số lượng</td>
                        <td class="title_total">Tổng Cộng</td>
                    </tr>
                </thead>
                <tbody id="tbody-cart">
                    <?php
                    if (!empty($list)):
                        foreach ($list AS $item):
                            if (empty($_SESSION['cart'][$item->id])) {
                                continue;
                            }
                            $item_qty = doubleval($_SESSION['cart'][$item->id]);
                            $item_total = $item_qty * $item->price;
                            $total += $item_total;
                            ?>
                            <tr>
                                <td class="image">
                                    <img style="border:none;" width="100" height="68" class="clsImage" src="/layouts/default/img/the-mot-nam.png" alt="" title="">
                                </td>
                                <td class="name">
                                    <span><?php echo $item->name ?></span>
                                </td>
                                <td class="cart_price"><span class="price_coupon"><?php echo number_format($item->price, 0, ',', '.'); ?> VNĐ</span><br></td>
                                <td class="quantity">
                                    <input type="text" value="<?php echo $item_qty; ?>" style="width:30px; text-align: center;" class="qty" name="product_<?php echo $item->id; ?>"/>
                                    <input type="image" src="/layouts/default/img/adept_update.png" alt="Submit" width="20" height="20" title="Cập nhập">
                                </td>
                                <td class="total"><span id="product_6634"><?php echo number_format($item_total, 0, ',', '.'); ?> VNĐ</span></td>
                            </tr>
                            <?php
                        endforeach;
                    endif;
                    ?>
                </tbody>
            </table>
        </div>

        <div class="cart-total">
            <div class="cart-total-left"> 
<!--             	<span class="btn btn-primary reload">Cập nhập giỏ hàng</span> -->
                <!--             	<button class="btn btn-primary">Cập nhập đơn hàng</button> -->
            </div>
            <div class="sub_total">
                <span>Thành Tiền : </span><span style="color:#b12704;" id="tongtien"><?php echo number_format($total, 0, ',', '.') ?></span> <span style="color:#b12704;">VNĐ</span>
                <div class="checkout">
                    <a style="font-size:13px;" href="javascript://" name="cart_checkout" title="" class="btn-cam" id="popupShowcart"><i class="fa fa-check-square-o"></i> Tiến hành thanh toán</a></div> 
            </div>
        </div>
        <div style="clear: both"></div>
        <div style="font-weight: normal; text-align:justify; color: #111; display: block; padding: 10px; background:#f6f6f6; border: 1px solid #cecece; border-radius: 3px;-moz-border-radius: 3px; -webkit-border-radius: 3px; font-size:13px;">
            <i style="color:#3b5998; font-size:18px;" class="fa fa-thumbs-up"></i> <strong style="color:#b12704;">Cam kết hoàn lại 100% tiền</strong> mua thẻ eDoctor trong thời gian 30 ngày kể từ ngày kích hoạt thẻ eDoctor, nếu quý khách hàng không hài lòng về chất lượng dịch vụ cũng như các quyền lợi được cung cấp, và không muốn tiếp tục sử dụng dịch vụ của eDoctor.
        </div>
        <div style="clear: both"></div>
    </form>
</div>