<h1 class="title-bg"><strong>Xác nhận đơn hàng</strong></h1>
<br />
<div id="sidebar">
    <?php echo $this->render('giohang.phtml'); ?>
    <br />
    <a href="/twopage.htm" class="btn-cam"><i class="fa fa-check-square-o"></i> Xác nhận đơn hàng và điền thông tin</a>
    <br />
    <a class="m-btn" href="/don-hang.htm"><i class="fa fa-pencil-square-o"></i> Sửa đơn hàng</a>
    <div class="note">
        <p style="font-size:13px; text-align:justify;"><i class="fa fa-hand-o-right"></i> <strong>Hoàn lại 100% tiền mua thẻ</strong> eDoctor nếu khách hàng không hài lòng và không muốn tiếp tục sử dụng dịch vụ tư vấn, chăm sóc sức khỏe của eDoctor trong 30 ngày đầu tiên kể từ ngày kích hoạt thẻ. </p>
    </div>
</div>