<?php
$list = $this->catList;
$totalRecords = $this->totalRecords;
$recordPerPage = $this->recordPerPage;
$pageNum = $totalRecords/$recordPerPage;
?>
<div class="row">
    <div class="span12">
        <div class="widget-block">
            <div class="widget-head">
                <h5><i class="black-icons list_images"></i> List</h5>
            </div>
            <div class="widget-content">
                <div class="widget-selectbox">
                    <ul>
                        <a class="btn btn-primary" href="<?php echo $this->contextPath ?>/add"><i class="icon-plus icon-white"></i> Add New</a>
                        <li class="right">
                            <div class="input-prepend"> <span class="add-on"><i class="icon-list-alt"></i></span>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="widget-box">
                    <table class="table task-tbl post-tbl table-striped">
                        <thead>
                            <tr>
                                <th width="5%" class="center">#</th>
                                <th width="">Tên danh mục</th>
                                <th width="">Đường dẫn</th>
                                <th width="10%" class="align-center">Thứ tự</th>
                                <th width="10%" class="align-center">Bài viết</th>
                                <th width="20%" class="align-center">Tuỳ chọn</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($list):
                                $i = 1;
                                foreach ($list AS $cat) :
                                    ?>
                                    <tr>
                                        <td class="center"><?php echo $i ?></td>
                                        <td><?php echo $cat['name']; ?></td>
                                        <td><?php echo $cat['slug']; ?></td>
                                        <td class="align-center"><?php echo $cat['order']; ?></td>
                                        <td class="align-center">
                                           
                                        </td>
                                        <td class="align-center">
                                            <a href="<?php echo $this->contextPath ?>/edit?id=<?php echo $cat['_id']; ?>" class="btn btn-success"><i class="icon-edit icon-white"></i> Edit</a>
                                            <a rel="<?php echo $this->contextPath ?>/delete?id=<?php echo $cat['_id']; ?>" class="btnDeleteRow btn btn-danger"><i class="icon-trash icon-white"></i> Delete</a>
                                        </td>
                                    </tr>
                                    <?php
                                    $i++;
                                endforeach;
                                ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>

                <div class="widget-bottom">
                    <div style="padding-bottom:15px;" class="widget-bottom">
                        <div class="pagination">
                            <ul class="pagination">
                                <?php if (isset($_GET['show'])) { ?>
                                    <?php if($pageNum > 1): 
                                    for ($i=0; $i <= $pageNum; $i++) { ?>
                                        <li <?php if( isset($_GET['page']) && $i+1 == $_GET['page']) echo 'class="active"'; ?>><a href="/admin/newscategory/index?show=<?php echo $_GET['show'];?>&page=<?php echo $i+1; ?>"><?php echo $i+1; ?></a></li>
                                    <?php } ?>
                                    <?php else: ?>
                                    <li class="active"><a tabindex="0">1</a></li>
                                    <?php endif; ?>
                                <?php } else { ?>
                                    <?php if($pageNum > 1): 
                                    for ($i=0; $i <= $pageNum; $i++) { ?>
                                        <li <?php if( isset($_GET['page']) && $i+1 == $_GET['page']) echo 'class="active"'; ?>><a href="/admin/newscategory/index?page=<?php echo $i+1; ?>"><?php echo $i+1; ?></a></li>
                                    <?php } ?>
                                    <?php else: ?>
                                    <li class="active"><a tabindex="0">1</a></li>
                                    <?php endif; ?>
                                <?php } ?>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<div class="widget-bottom">
    <div><?php echo $this->page_title ?></div>
</div>